#include <stdint.h>

static const uint64_t args_w_Wh_16760833_512_10843986_32_16_8_4_2[0x18] = {

    // 32-NTT: 11680345^i, Jump 16
    [0x0] = 0x0000008000000001LLU,       [0x8] = 0x497e62cf0092d807LLU,
    [0x1] = 0x52190af100a4090aLLU,       [0x9] = 0x1d275d3a003a4027LLU,
    [0x2] = 0x188562400030fe82LLU,       [0xa] = 0x3f11c833007e0408LLU,
    [0x3] = 0x16b0e5a3002d5673LLU,       [0xb] = 0x576462c100ae9d14LLU,
    [0x4] = 0x37396d24006e573eLLU,       [0xc] = 0x35394d1e006a57feLLU,
    [0x5] = 0x182e8489003050f2LLU,       [0xd] = 0x7f342c8c00fe28c0LLU,
    [0x6] = 0x7c36200c00f82e26LLU,       [0xe] = 0x573fa59200ae53acLLU,
    [0x7] = 0x48cce1f00091755eLLU,       [0xf] = 0x36ee3cd8006dc103LLU,

    // 16-NTT: 11680345^i, Jump 32
    [0x10] = 0x0000008000000001LLU,      [0x14] = 0x497e62cf0092d807LLU,
    [0x11] = 0x188562400030fe82LLU,      [0x15] = 0x3f11c833007e0408LLU,
    [0x12] = 0x37396d24006e573eLLU,      [0x16] = 0x35394d1e006a57feLLU,
    [0x13] = 0x7c36200c00f82e26LLU,      [0x17] = 0x573fa59200ae53acLLU,

    // 8_4_2-NTT: there's no reload on twiddle factors (generated by trn1/2)
};

static const uint64_t args_w_Wh_16760833_512_11680345_512_256_128_64[0x1e0] = {

    /* permutate for the NTT implementation: ntt512x3_512_256_128_64
    register    (v25.4S)(v24.4S)                          (v27.4S)(v26.4S)
    ==========================================================================
    512-NTT         0 -  63                                  64 - 128
    512-NTT       129 - 191                                 192 - 255
    256-NTT         0 -  63                                  64 - 128
    128-NTT         0 -  63                                    N/A
    */

    [0x000] = 0x0000008000000001LLU,          [0x004] = 0x4ac6b2e200956803LLU,    // 0, 64
    [0x001] = 0x5933790500b23a59LLU,          [0x005] = 0x64b57f7b00c938a5LLU,    // 1, 65
    [0x002] = 0x51d3cea200a37eb4LLU,          [0x006] = 0x459def36008b1910LLU,    // 2, 66
    [0x003] = 0x1bf95c3b0037e4bcLLU,          [0x007] = 0x4fc78b93009f6734LLU,    // 3, 67
    
    [0x008] = 0x36819d31006ce7faLLU,          [0x00c] = 0x48c692dc009168c3LLU,    // 128, 192
    [0x009] = 0x1c998fc7003924d3LLU,          [0x00d] = 0x673c0c1c00ce447bLLU,    // 129, 193
    [0x00a] = 0x3491872d006908c6LLU,          [0x00e] = 0x69f195fc00d3ae34LLU,    // 130, 194
    [0x00b] = 0x3caa6a5e00793680LLU,          [0x00f] = 0x59e0623f00b393d5LLU,    // 131, 195
    
    [0x010] = 0x0000008000000001LLU,          [0x014] = 0x36819d31006ce7faLLU,    // 0, 128
    [0x011] = 0x51d3cea200a37eb4LLU,          [0x015] = 0x3491872d006908c6LLU,    // 2, 130
    [0x012] = 0x59ab567c00b329d8LLU,          [0x016] = 0x28a7181d005139ddLLU,    // 4, 132
    [0x013] = 0x71f5f40b00e3b2eeLLU,          [0x017] = 0x2e0fb2bf005c085eLLU,    // 6, 134
    
    [0x018] = 0x0000008000000001LLU,    // 0
    [0x019] = 0x59ab567c00b329d8LLU,    // 4
    [0x01a] = 0x12162ffa00242355LLU,    // 8
    [0x01b] = 0x5c24ecdf00b81bc8LLU,    // 12

    [0x01c] = 0x59ab567c00b329d8LLU,          [0x020] = 0x7e492e4d00fc5339LLU,    // 4, 68
    [0x01d] = 0x205890040040a0f4LLU,          [0x021] = 0x2dac28dd005b417cLLU,    // 5, 69
    [0x01e] = 0x71f5f40b00e3b2eeLLU,          [0x022] = 0x4b74cde80096c3e2LLU,    // 6, 70
    [0x01f] = 0x077b40c9000ef2c4LLU,          [0x023] = 0x5d95c49400bafcbfLLU,    // 7, 71
    
    [0x024] = 0x28a7181d005139ddLLU,          [0x028] = 0x64da3caa00c9820dLLU,    // 132, 196
    [0x025] = 0x41faf67c0083d4f0LLU,          [0x029] = 0x30098a33005ffb10LLU,    // 133, 197
    [0x026] = 0x2e0fb2bf005c085eLLU,          [0x02a] = 0x73bfa2f500e74567LLU,    // 134, 198
    [0x027] = 0x5a7f8d0900b4d1dbLLU,          [0x02b] = 0x76e37f6900ed8b8eLLU,    // 135, 199
    
    [0x02c] = 0x12162ffa00242355LLU,          [0x030] = 0x6c6359ea00d89083LLU,    // 8, 136
    [0x02d] = 0x2f55a339005e939cLLU,          [0x031] = 0x5c2930f000b8244eLLU,    // 10, 138
    [0x02e] = 0x5c24ecdf00b81bc8LLU,          [0x032] = 0x3be88ee80077b32aLLU,    // 12, 140
    [0x02f] = 0x4895578d00910665LLU,          [0x033] = 0x1374e7a60026e015LLU,    // 14, 142
    
    [0x034] = 0x4911c3280091fefeLLU,    // 16
    [0x035] = 0x7403cbff00e7cd97LLU,    // 20
    [0x036] = 0x222a20660044432cLLU,    // 24
    [0x037] = 0x3a0206480073e70cLLU,    // 28

    [0x038] = 0x12162ffa00242355LLU,          [0x03c] = 0x2634496c004c5579LLU,    // 8, 72
    [0x039] = 0x2c58d00800589b74LLU,          [0x03d] = 0x2e02f910005beef1LLU,    // 9, 73
    [0x03a] = 0x2f55a339005e939cLLU,          [0x03e] = 0x58c3878900b15aaeLLU,    // 10, 74
    [0x03b] = 0x59b6b65400b34092LLU,          [0x03f] = 0x6606913e00cbda20LLU,    // 11, 75
    
    [0x040] = 0x6c6359ea00d89083LLU,          [0x044] = 0x76f0a3b200eda5d0LLU,    // 136, 200
    [0x041] = 0x35ad6824006b3ffaLLU,          [0x045] = 0x30805a660060e875LLU,    // 137, 201
    [0x042] = 0x5c2930f000b8244eLLU,          [0x046] = 0x4c180fb800980a14LLU,    // 138, 202
    [0x043] = 0x66557ef900cc77d4LLU,          [0x047] = 0x55bfd72000ab54cfLLU,    // 139, 203
    
    [0x048] = 0x4911c3280091fefeLLU,          [0x04c] = 0x37331e10006e4aa3LLU,    // 16, 144
    [0x049] = 0x60d507e100c179a6LLU,          [0x04d] = 0x1d20b811003a32e0LLU,    // 18, 146
    [0x04a] = 0x7403cbff00e7cd97LLU,          [0x04e] = 0x485a96dd00909101LLU,    // 20, 148
    [0x04b] = 0x546d5b0200a8b080LLU,          [0x04f] = 0x04e515c10009c7b9LLU,    // 22, 150
    
    [0x050] = 0x28c05a6e00516c55LLU,    // 32
    [0x051] = 0x6b98199b00d6fa68LLU,    // 36
    [0x052] = 0x0baddb6b001755e0LLU,    // 40
    [0x053] = 0x1ec5b84f003d7c0eLLU,    // 44

    [0x054] = 0x5c24ecdf00b81bc8LLU,          [0x058] = 0x727f5de500e4c57dLLU,    // 12, 76
    [0x055] = 0x199bfde600332b2eLLU,          [0x059] = 0x72c3435e00e54d26LLU,    // 13, 77
    [0x056] = 0x4895578d00910665LLU,          [0x05a] = 0x7a8fd1fa00f4e25dLLU,    // 14, 78
    [0x057] = 0x7201acf900e3ca5aLLU,          [0x05b] = 0x315a91f300629c77LLU,    // 15, 79
    
    [0x05c] = 0x3be88ee80077b32aLLU,          [0x060] = 0x5ab4b9d400b53c1aLLU,    // 140, 204
    [0x05d] = 0x6169cc9200c2a2e5LLU,          [0x061] = 0x302a39de00603c5fLLU,    // 141, 205
    [0x05e] = 0x1374e7a60026e015LLU,          [0x062] = 0x0c5c44050018b25aLLU,    // 142, 206
    [0x05f] = 0x51dd658800a391ddLLU,          [0x063] = 0x7eb75a5800fd2f5aLLU,    // 143, 207
    
    [0x064] = 0x222a20660044432cLLU,          [0x068] = 0x0b60991b0016bb82LLU,    // 24, 152
    [0x065] = 0x62785ab400c4bf7aLLU,          [0x069] = 0x07676ad3000ecb22LLU,    // 26, 154
    [0x066] = 0x3a0206480073e70cLLU,          [0x06a] = 0x1fd5663a003f9ae2LLU,    // 28, 156
    [0x067] = 0x48143d4700900471LLU,          [0x06b] = 0x011d19c5000239a5LLU,    // 30, 158
    
    [0x06c] = 0x00cbd37400019741LLU,    // 48
    [0x06d] = 0x2b0005d60055ea8cLLU,    // 52
    [0x06e] = 0x5de87ec200bba20aLLU,    // 56
    [0x06f] = 0x19f6cb990033e09cLLU,    // 60

    [0x070] = 0x4911c3280091fefeLLU,          [0x074] = 0x289b9d3f005122edLLU,    // 16, 80
    [0x071] = 0x1f01e65b003df44cLLU,          [0x075] = 0x3553128f006a8b7cLLU,    // 17, 81
    [0x072] = 0x60d507e100c179a6LLU,          [0x076] = 0x43bc12c100875648LLU,    // 18, 82
    [0x073] = 0x6863426800d09254LLU,          [0x077] = 0x32cc01ce00657e9eLLU,    // 19, 83
    
    [0x078] = 0x37331e10006e4aa3LLU,          [0x07c] = 0x694f1a5d00d2698eLLU,    // 144, 208
    [0x079] = 0x2ced712f0059c46cLLU,          [0x07d] = 0x5d55838400ba7c5dLLU,    // 145, 209
    [0x07a] = 0x1d20b811003a32e0LLU,          [0x07e] = 0x43fd6e980087d8dfLLU,    // 146, 210
    [0x07b] = 0x05d200fa000ba119LLU,          [0x07f] = 0x739cf4ca00e7001cLLU,    // 147, 211
    
    [0x080] = 0x28c05a6e00516c55LLU,          [0x084] = 0x03c9dff4000791dbLLU,    // 32, 160
    [0x081] = 0x67b42a2300cf347bLLU,          [0x085] = 0x1ea83e71003d4129LLU,    // 34, 162
    [0x082] = 0x6b98199b00d6fa68LLU,          [0x086] = 0x1ef2da98003dd63cLLU,    // 36, 164
    [0x083] = 0x511dbe9f00a212efLLU,          [0x087] = 0x78ef615f00f1a24cLLU,    // 38, 166
    
    [0x088] = 0x4ac6b2e200956803LLU,    // 64
    [0x089] = 0x7e492e4d00fc5339LLU,    // 68
    [0x08a] = 0x2634496c004c5579LLU,    // 72
    [0x08b] = 0x727f5de500e4c57dLLU,    // 76

    [0x08c] = 0x7403cbff00e7cd97LLU,          [0x090] = 0x22539ec500449614LLU,    // 20, 84
    [0x08d] = 0x08d4dfaf0011a555LLU,          [0x091] = 0x4646143f008c6906LLU,    // 21, 85
    [0x08e] = 0x546d5b0200a8b080LLU,          [0x092] = 0x629b737a00c5059aLLU,    // 22, 86
    [0x08f] = 0x684108da00d04df2LLU,          [0x093] = 0x4b3783160096496bLLU,    // 23, 87
    
    [0x094] = 0x485a96dd00909101LLU,          [0x098] = 0x7530ae3600ea26c5LLU,    // 148, 212
    [0x095] = 0x139717b200272464LLU,          [0x099] = 0x67317bf800ce2f60LLU,    // 149, 213
    [0x096] = 0x04e515c10009c7b9LLU,          [0x09a] = 0x4896685100910886LLU,    // 150, 214
    [0x097] = 0x3a72de7d0074c884LLU,          [0x09b] = 0x589650bc00b10057LLU,    // 151, 215
    
    [0x09c] = 0x0baddb6b001755e0LLU,          [0x0a0] = 0x59fcf16200b3cce5LLU,    // 40, 168
    [0x09d] = 0x7d7aa42c00fab68cLLU,          [0x0a1] = 0x76487ca900ec55d6LLU,    // 42, 170
    [0x09e] = 0x1ec5b84f003d7c0eLLU,          [0x0a2] = 0x37da8068006f9914LLU,    // 44, 172
    [0x09f] = 0x4e3b5b89009c4f9aLLU,          [0x0a3] = 0x133610f100266287LLU,    // 46, 174
    
    [0x0a4] = 0x289b9d3f005122edLLU,    // 80
    [0x0a5] = 0x22539ec500449614LLU,    // 84
    [0x0a6] = 0x5efc1aa800bdc8b8LLU,    // 88
    [0x0a7] = 0x2839e15000505fa6LLU,    // 92

    [0x0a8] = 0x222a20660044432cLLU,          [0x0ac] = 0x5efc1aa800bdc8b8LLU,    // 24, 88
    [0x0a9] = 0x72dcc93f00e58025LLU,          [0x0ad] = 0x2c461cdb00587617LLU,    // 25, 89
    [0x0aa] = 0x62785ab400c4bf7aLLU,          [0x0ae] = 0x5724f16500ae1e51LLU,    // 26, 90
    [0x0ab] = 0x11b100ae00235929LLU,          [0x0af] = 0x02e741ce0005cd10LLU,    // 27, 91
    
    [0x0b0] = 0x0b60991b0016bb82LLU,          [0x0b4] = 0x7cfca9ad00f9bad6LLU,    // 152, 216
    [0x0b1] = 0x4bf955090097ccaeLLU,          [0x0b5] = 0x2cdf40230059a811LLU,    // 153, 217
    [0x0b2] = 0x07676ad3000ecb22LLU,          [0x0b6] = 0x469825c3008d0d00LLU,    // 154, 218
    [0x0b3] = 0x4813d5ad009003a2LLU,          [0x0b7] = 0x44edda320089b93eLLU,    // 155, 219
    
    [0x0b8] = 0x00cbd37400019741LLU,          [0x0bc] = 0x67d17b7700cf6f0fLLU,    // 48, 176
    [0x0b9] = 0x044ac02c0008935bLLU,          [0x0bd] = 0x36dc3957006d9d05LLU,    // 50, 178
    [0x0ba] = 0x2b0005d60055ea8cLLU,          [0x0be] = 0x79c3d37b00f34ac6LLU,    // 52, 180
    [0x0bb] = 0x7670882c00eca5d9LLU,          [0x0bf] = 0x272972b6004e3f51LLU,    // 54, 182
    
    [0x0c0] = 0x40ee37cd0081bbf9LLU,    // 96
    [0x0c1] = 0x7449706800e858bdLLU,    // 100
    [0x0c2] = 0x798e441700f2dfc2LLU,    // 104
    [0x0c3] = 0x7559d68000ea7901LLU,    // 108

    [0x0c4] = 0x3a0206480073e70cLLU,          [0x0c8] = 0x2839e15000505fa6LLU,    // 28, 92
    [0x0c5] = 0x7de26d9e00fb85ebLLU,          [0x0c9] = 0x42dda8a7008599e3LLU,    // 29, 93
    [0x0c6] = 0x48143d4700900471LLU,          [0x0ca] = 0x3b987ee400771332LLU,    // 30, 94
    [0x0c7] = 0x407441500080c849LLU,          [0x0cb] = 0x7f626c1c00fe8528LLU,    // 31, 95
    
    [0x0cc] = 0x1fd5663a003f9ae2LLU,          [0x0d0] = 0x10a057850021385fLLU,    // 156, 220
    [0x0cd] = 0x7e7c459300fcb94eLLU,          [0x0d1] = 0x7639cafd00ec387aLLU,    // 157, 221
    [0x0ce] = 0x011d19c5000239a5LLU,          [0x0d2] = 0x55a97e0a00ab2828LLU,    // 158, 222
    [0x0cf] = 0x66293be900cc1f64LLU,          [0x0d3] = 0x5153e92900a27f29LLU,    // 159, 223
    
    [0x0d4] = 0x5de87ec200bba20aLLU,          [0x0d8] = 0x792cff4700f21d69LLU,    // 56, 184
    [0x0d5] = 0x2b3ed08900566802LLU,          [0x0d9] = 0x63431ae300c65495LLU,    // 58, 186
    [0x0d6] = 0x19f6cb990033e09cLLU,          [0x0da] = 0x713ed6c400e2450fLLU,    // 60, 188
    [0x0d7] = 0x5c1ce1dc00b80bb6LLU,          [0x0db] = 0x4cf874d00099ca6eLLU,    // 62, 190
    
    [0x0dc] = 0x62d8a2c600c57fdaLLU,    // 112
    [0x0dd] = 0x6931a27f00d22eadLLU,    // 116
    [0x0de] = 0x5401961200a7d92cLLU,    // 120
    [0x0df] = 0x109de06700213372LLU,    // 124

    [0x0e0] = 0x28c05a6e00516c55LLU,          [0x0e4] = 0x40ee37cd0081bbf9LLU,    // 32, 96
    [0x0e1] = 0x1fbead8c003f6d7cLLU,          [0x0e5] = 0x580359fe00afdab3LLU,    // 33, 97
    [0x0e2] = 0x67b42a2300cf347bLLU,          [0x0e6] = 0x6e8059a800dcc974LLU,    // 34, 98
    [0x0e3] = 0x2b6652e90056b6f3LLU,          [0x0e7] = 0x55afa81400ab3479LLU,    // 35, 99
    
    [0x0e8] = 0x03c9dff4000791dbLLU,          [0x0ec] = 0x677a9dc000cec17fLLU,    // 160, 224
    [0x0e9] = 0x45b7c4ab008b4caeLLU,          [0x0ed] = 0x70d6f1cc00e17579LLU,    // 161, 225
    [0x0ea] = 0x1ea83e71003d4129LLU,          [0x0ee] = 0x0d14a19b001a22b9LLU,    // 162, 226
    [0x0eb] = 0x312cf38c00624151LLU,          [0x0ef] = 0x16c8870b002d85aaLLU,    // 163, 227
    
    [0x0f0] = 0x4ac6b2e200956803LLU,          [0x0f4] = 0x48c692dc009168c3LLU,    // 64, 192
    [0x0f1] = 0x459def36008b1910LLU,          [0x0f5] = 0x69f195fc00d3ae34LLU,    // 66, 194
    [0x0f2] = 0x7e492e4d00fc5339LLU,          [0x0f6] = 0x64da3caa00c9820dLLU,    // 68, 196
    [0x0f3] = 0x4b74cde80096c3e2LLU,          [0x0f7] = 0x73bfa2f500e74567LLU,    // 70, 198
    
    [0x0f8] = 0x36819d31006ce7faLLU,    // 128
    [0x0f9] = 0x28a7181d005139ddLLU,    // 132
    [0x0fa] = 0x6c6359ea00d89083LLU,    // 136
    [0x0fb] = 0x3be88ee80077b32aLLU,    // 140

    [0x0fc] = 0x6b98199b00d6fa68LLU,          [0x100] = 0x7449706800e858bdLLU,    // 36, 100
    [0x0fd] = 0x2b51a0bd00568d99LLU,          [0x101] = 0x392e94ec00724093LLU,    // 37, 101
    [0x0fe] = 0x511dbe9f00a212efLLU,          [0x102] = 0x7b0fe57e00f5e244LLU,    // 38, 102
    [0x0ff] = 0x7ac310c900f548c1LLU,          [0x103] = 0x7458ce3f00e87771LLU,    // 39, 103
    
    [0x104] = 0x1ef2da98003dd63cLLU,          [0x108] = 0x3ff16a1b007fc2dcLLU,    // 164, 228
    [0x105] = 0x456edff3008abb09LLU,          [0x109] = 0x3373ac380066cd9fLLU,    // 165, 229
    [0x106] = 0x78ef615f00f1a24cLLU,          [0x10a] = 0x56e4b4d600ad9df8LLU,    // 166, 230
    [0x107] = 0x7b9f1bcb00f70069LLU,          [0x10b] = 0x437fa8270086dd91LLU,    // 167, 231
    
    [0x10c] = 0x2634496c004c5579LLU,          [0x110] = 0x76f0a3b200eda5d0LLU,    // 72, 200
    [0x10d] = 0x58c3878900b15aaeLLU,          [0x111] = 0x4c180fb800980a14LLU,    // 74, 202
    [0x10e] = 0x727f5de500e4c57dLLU,          [0x112] = 0x5ab4b9d400b53c1aLLU,    // 76, 204
    [0x10f] = 0x7a8fd1fa00f4e25dLLU,          [0x113] = 0x0c5c44050018b25aLLU,    // 78, 206
    
    [0x114] = 0x37331e10006e4aa3LLU,    // 144
    [0x115] = 0x485a96dd00909101LLU,    // 148
    [0x116] = 0x0b60991b0016bb82LLU,    // 152
    [0x117] = 0x1fd5663a003f9ae2LLU,    // 156

    [0x118] = 0x0baddb6b001755e0LLU,          [0x11c] = 0x798e441700f2dfc2LLU,    // 40, 104
    [0x119] = 0x03accf30000757c8LLU,          [0x11d] = 0x5634263300ac3d33LLU,    // 41, 105
    [0x11a] = 0x7d7aa42c00fab68cLLU,          [0x11e] = 0x587c944d00b0ccebLLU,    // 42, 106
    [0x11b] = 0x0f1f3e40001e36edLLU,          [0x11f] = 0x1a2999cc0034461fLLU,    // 43, 107
    
    [0x120] = 0x59fcf16200b3cce5LLU,          [0x124] = 0x4e4620ba009c651fLLU,    // 168, 232
    [0x121] = 0x6e03ed0d00dbd0d9LLU,          [0x125] = 0x5b0f0d6800b5f094LLU,    // 169, 233
    [0x122] = 0x76487ca900ec55d6LLU,          [0x126] = 0x63c973f900c76104LLU,    // 170, 234
    [0x123] = 0x38de8e6b0071a0aeLLU,          [0x127] = 0x789686a900f0f0c3LLU,    // 171, 235
    
    [0x128] = 0x289b9d3f005122edLLU,          [0x12c] = 0x694f1a5d00d2698eLLU,    // 80, 208
    [0x129] = 0x43bc12c100875648LLU,          [0x12d] = 0x43fd6e980087d8dfLLU,    // 82, 210
    [0x12a] = 0x22539ec500449614LLU,          [0x12e] = 0x7530ae3600ea26c5LLU,    // 84, 212
    [0x12b] = 0x629b737a00c5059aLLU,          [0x12f] = 0x4896685100910886LLU,    // 86, 214
    
    [0x130] = 0x03c9dff4000791dbLLU,    // 160
    [0x131] = 0x1ef2da98003dd63cLLU,    // 164
    [0x132] = 0x59fcf16200b3cce5LLU,    // 168
    [0x133] = 0x37da8068006f9914LLU,    // 172

    [0x134] = 0x1ec5b84f003d7c0eLLU,          [0x138] = 0x7559d68000ea7901LLU,    // 44, 108
    [0x135] = 0x25a35a31004b33e3LLU,          [0x139] = 0x4c0577920097e4edLLU,    // 45, 109
    [0x136] = 0x4e3b5b89009c4f9aLLU,          [0x13a] = 0x4e6aac5d009cae24LLU,    // 46, 110
    [0x137] = 0x4a63c3a70094a256LLU,          [0x13b] = 0x4692db70008d026eLLU,    // 47, 111
    
    [0x13c] = 0x37da8068006f9914LLU,          [0x140] = 0x2866d98e0050b980LLU,    // 172, 236
    [0x13d] = 0x348a74690068faa4LLU,          [0x141] = 0x1dc578c0003b7c0fLLU,    // 173, 237
    [0x13e] = 0x133610f100266287LLU,          [0x142] = 0x0cccb7a100199309LLU,    // 174, 238
    [0x13f] = 0x3538ccfe006a56feLLU,          [0x143] = 0x02cb80dd0005959cLLU,    // 175, 239
    
    [0x144] = 0x5efc1aa800bdc8b8LLU,          [0x148] = 0x7cfca9ad00f9bad6LLU,    // 88, 216
    [0x145] = 0x5724f16500ae1e51LLU,          [0x149] = 0x469825c3008d0d00LLU,    // 90, 218
    [0x146] = 0x2839e15000505fa6LLU,          [0x14a] = 0x10a057850021385fLLU,    // 92, 220
    [0x147] = 0x3b987ee400771332LLU,          [0x14b] = 0x55a97e0a00ab2828LLU,    // 94, 222
    
    [0x14c] = 0x67d17b7700cf6f0fLLU,    // 176
    [0x14d] = 0x79c3d37b00f34ac6LLU,    // 180
    [0x14e] = 0x792cff4700f21d69LLU,    // 184
    [0x14f] = 0x713ed6c400e2450fLLU,    // 188

    [0x150] = 0x00cbd37400019741LLU,          [0x154] = 0x62d8a2c600c57fdaLLU,    // 48, 112
    [0x151] = 0x7b78c33500f6b3cbLLU,          [0x155] = 0x1fc22ceb003f7479LLU,    // 49, 113
    [0x152] = 0x044ac02c0008935bLLU,          [0x156] = 0x4468e2740088af91LLU,    // 50, 114
    [0x153] = 0x0bf25a0b0017debbLLU,          [0x157] = 0x009153d40001225fLLU,    // 51, 115
    
    [0x158] = 0x67d17b7700cf6f0fLLU,          [0x15c] = 0x2de6f50f005bb6f7LLU,    // 176, 240
    [0x159] = 0x66936ef500ccf395LLU,          [0x15d] = 0x2d7f42a3005ae7c6LLU,    // 177, 241
    [0x15a] = 0x36dc3957006d9d05LLU,          [0x15e] = 0x7bca028500f75621LLU,    // 178, 242
    [0x15b] = 0x566055bf00ac957cLLU,          [0x15f] = 0x0e2a9a98001c4e20LLU,    // 179, 243
    
    [0x160] = 0x40ee37cd0081bbf9LLU,          [0x164] = 0x677a9dc000cec17fLLU,    // 96, 224
    [0x161] = 0x6e8059a800dcc974LLU,          [0x165] = 0x0d14a19b001a22b9LLU,    // 98, 226
    [0x162] = 0x7449706800e858bdLLU,          [0x166] = 0x3ff16a1b007fc2dcLLU,    // 100, 228
    [0x163] = 0x7b0fe57e00f5e244LLU,          [0x167] = 0x56e4b4d600ad9df8LLU,    // 102, 230
    
    [0x168] = 0x48c692dc009168c3LLU,    // 192
    [0x169] = 0x64da3caa00c9820dLLU,    // 196
    [0x16a] = 0x76f0a3b200eda5d0LLU,    // 200
    [0x16b] = 0x5ab4b9d400b53c1aLLU,    // 204

    [0x16c] = 0x2b0005d60055ea8cLLU,          [0x170] = 0x6931a27f00d22eadLLU,    // 52, 116
    [0x16d] = 0x037261950006e30aLLU,          [0x171] = 0x4dad00f3009b332cLLU,    // 53, 117
    [0x16e] = 0x7670882c00eca5d9LLU,          [0x172] = 0x5c04282e00b7da4fLLU,    // 54, 118
    [0x16f] = 0x5a4a8dc900b467f7LLU,          [0x173] = 0x5e8d820200bcebbeLLU,    // 55, 119
    
    [0x174] = 0x79c3d37b00f34ac6LLU,          [0x178] = 0x11dc2cf90023af6cLLU,    // 180, 244
    [0x175] = 0x3e97270b007d0f03LLU,          [0x179] = 0x5d22653c00ba163aLLU,    // 181, 245
    [0x176] = 0x272972b6004e3f51LLU,          [0x17a] = 0x0fbbdf68001f6fe1LLU,    // 182, 246
    [0x177] = 0x439bbcac008715acLLU,          [0x17b] = 0x5f5339ef00be76cbLLU,    // 183, 247
    
    [0x17c] = 0x798e441700f2dfc2LLU,          [0x180] = 0x4e4620ba009c651fLLU,    // 104, 232
    [0x17d] = 0x587c944d00b0ccebLLU,          [0x181] = 0x63c973f900c76104LLU,    // 106, 234
    [0x17e] = 0x7559d68000ea7901LLU,          [0x182] = 0x2866d98e0050b980LLU,    // 108, 236
    [0x17f] = 0x4e6aac5d009cae24LLU,          [0x183] = 0x0cccb7a100199309LLU,    // 110, 238
    
    [0x184] = 0x694f1a5d00d2698eLLU,    // 208
    [0x185] = 0x7530ae3600ea26c5LLU,    // 212
    [0x186] = 0x7cfca9ad00f9bad6LLU,    // 216
    [0x187] = 0x10a057850021385fLLU,    // 220

    [0x188] = 0x5de87ec200bba20aLLU,          [0x18c] = 0x5401961200a7d92cLLU,    // 56, 120
    [0x189] = 0x7548ffcb00ea575cLLU,          [0x18d] = 0x68ba149c00d13fcdLLU,    // 57, 121
    [0x18a] = 0x2b3ed08900566802LLU,          [0x18e] = 0x662069b400cc0dc4LLU,    // 58, 122
    [0x18b] = 0x4343a1a5008665a2LLU,          [0x18f] = 0x5894e6e100b0fd84LLU,    // 59, 123
    
    [0x190] = 0x792cff4700f21d69LLU,          [0x194] = 0x4759879b008e8f63LLU,    // 184, 248
    [0x191] = 0x51993efe00a309b2LLU,          [0x195] = 0x604f45f100c06e65LLU,    // 185, 249
    [0x192] = 0x63431ae300c65495LLU,          [0x196] = 0x131942be002628f9LLU,    // 186, 250
    [0x193] = 0x6893c30800d0f33dLLU,          [0x197] = 0x44b98c1e008950bcLLU,    // 187, 251
    
    [0x198] = 0x62d8a2c600c57fdaLLU,          [0x19c] = 0x2de6f50f005bb6f7LLU,    // 112, 240
    [0x199] = 0x4468e2740088af91LLU,          [0x19d] = 0x7bca028500f75621LLU,    // 114, 242
    [0x19a] = 0x6931a27f00d22eadLLU,          [0x19e] = 0x11dc2cf90023af6cLLU,    // 116, 244
    [0x19b] = 0x5c04282e00b7da4fLLU,          [0x19f] = 0x0fbbdf68001f6fe1LLU,    // 118, 246
    
    [0x1a0] = 0x677a9dc000cec17fLLU,    // 224
    [0x1a1] = 0x3ff16a1b007fc2dcLLU,    // 228
    [0x1a2] = 0x4e4620ba009c651fLLU,    // 232
    [0x1a3] = 0x2866d98e0050b980LLU,    // 236

    [0x1a4] = 0x19f6cb990033e09cLLU,          [0x1a8] = 0x109de06700213372LLU,    // 60, 124
    [0x1a5] = 0x0143ea7900028733LLU,          [0x1a9] = 0x13aead1800275383LLU,    // 61, 125
    [0x1a6] = 0x5c1ce1dc00b80bb6LLU,          [0x1aa] = 0x4558aae5008a8eaaLLU,    // 62, 126
    [0x1a7] = 0x1c6d2aae0038cc1fLLU,          [0x1ab] = 0x06089a20000c0e30LLU,    // 63, 127
    
    [0x1ac] = 0x713ed6c400e2450fLLU,          [0x1b0] = 0x5b52d55a00b67802LLU,    // 188, 252
    [0x1ad] = 0x7018a0b800dff936LLU,          [0x1b1] = 0x5cb91e6b00b943e1LLU,    // 189, 253
    [0x1ae] = 0x4cf874d00099ca6eLLU,          [0x1b2] = 0x5390a75600a6f787LLU,    // 190, 254
    [0x1af] = 0x45a13b09008b1fa6LLU,          [0x1b3] = 0x2d2fa33c005a48afLLU,    // 191, 255
    
    [0x1b4] = 0x5401961200a7d92cLLU,          [0x1b8] = 0x4759879b008e8f63LLU,    // 120, 248
    [0x1b5] = 0x662069b400cc0dc4LLU,          [0x1b9] = 0x131942be002628f9LLU,    // 122, 250
    [0x1b6] = 0x109de06700213372LLU,          [0x1ba] = 0x5b52d55a00b67802LLU,    // 124, 252
    [0x1b7] = 0x4558aae5008a8eaaLLU,          [0x1bb] = 0x5390a75600a6f787LLU,    // 126, 254
    
    [0x1bc] = 0x2de6f50f005bb6f7LLU,    // 240
    [0x1bd] = 0x11dc2cf90023af6cLLU,    // 244
    [0x1be] = 0x4759879b008e8f63LLU,    // 248
    [0x1bf] = 0x5b52d55a00b67802LLU,    // 252

    [0x1c0] = 0x0000008000000001LLU,          [0x1d0] = 0x36819d31006ce7faLLU,
    [0x1c1] = 0x12162ffa00242355LLU,          [0x1d1] = 0x6c6359ea00d89083LLU,
    [0x1c2] = 0x4911c3280091fefeLLU,          [0x1d2] = 0x37331e10006e4aa3LLU,
    [0x1c3] = 0x222a20660044432cLLU,          [0x1d3] = 0x0b60991b0016bb82LLU,

    [0x1c4] = 0x28c05a6e00516c55LLU,          [0x1d4] = 0x03c9dff4000791dbLLU,
    [0x1c5] = 0x0baddb6b001755e0LLU,          [0x1d5] = 0x59fcf16200b3cce5LLU,
    [0x1c6] = 0x00cbd37400019741LLU,          [0x1d6] = 0x67d17b7700cf6f0fLLU,
    [0x1c7] = 0x5de87ec200bba20aLLU,          [0x1d7] = 0x792cff4700f21d69LLU,

    [0x1c8] = 0x4ac6b2e200956803LLU,          [0x1d8] = 0x48c692dc009168c3LLU,
    [0x1c9] = 0x2634496c004c5579LLU,          [0x1d9] = 0x76f0a3b200eda5d0LLU,
    [0x1ca] = 0x289b9d3f005122edLLU,          [0x1da] = 0x694f1a5d00d2698eLLU,
    [0x1cb] = 0x5efc1aa800bdc8b8LLU,          [0x1db] = 0x7cfca9ad00f9bad6LLU,

    [0x1cc] = 0x40ee37cd0081bbf9LLU,          [0x1dc] = 0x677a9dc000cec17fLLU,
    [0x1cd] = 0x798e441700f2dfc2LLU,          [0x1dd] = 0x4e4620ba009c651fLLU,
    [0x1ce] = 0x62d8a2c600c57fdaLLU,          [0x1de] = 0x2de6f50f005bb6f7LLU,
    [0x1cf] = 0x5401961200a7d92cLLU,          [0x1df] = 0x4759879b008e8f63LLU,
};

static const uint64_t args_w_Wh_16760833_512_10843986_512_256_128_64[0x1e0] = {

    /* permutate for the NTT implementation: ntt512x3_512_256_128_64
    register    (v25.4S)(v24.4S)                          (v27.4S)(v26.4S)
    ==========================================================================
    512-NTT         0 -  63                                  64 - 128
    512-NTT       129 - 191                                 192 - 255
    256-NTT         0 -  63                                  64 - 128
    128-NTT         0 -  63                                    N/A
    */

    [0x000] = 0x0000008000000001LLU,          [0x004] = 0x37396d24006e573eLLU,    // 0, 64
    [0x001] = 0x52d05cc400a57752LLU,          [0x005] = 0x3a5ec4f70074a05bLLU,    // 1, 65
    [0x002] = 0x2c6f58aa0058c87aLLU,          [0x006] = 0x33078b300065f593LLU,    // 2, 66
    [0x003] = 0x2346e19500467c20LLU,          [0x007] = 0x0fe75f48001fc6cbLLU,    // 3, 67
    
    [0x008] = 0x497e62cf0092d807LLU,          [0x00c] = 0x35394d1e006a57feLLU,    // 128, 192
    [0x009] = 0x79f765e000f3b1d1LLU,          [0x00d] = 0x6392d55200c6f3e2LLU,    // 129, 193
    [0x00a] = 0x3aa7551b00753157LLU,          [0x00e] = 0x23e31e240047b44bLLU,    // 130, 194
    [0x00b] = 0x6c5152e800d86c7eLLU,          [0x00f] = 0x7ebc158700fd38ceLLU,    // 131, 195
    
    [0x010] = 0x0000008000000001LLU,          [0x014] = 0x497e62cf0092d807LLU,    // 0, 128
    [0x011] = 0x2c6f58aa0058c87aLLU,          [0x015] = 0x3aa7551b00753157LLU,    // 2, 130
    [0x012] = 0x24ad2aa6004947ffLLU,          [0x016] = 0x6f621f9900de8c8fLLU,    // 4, 132
    [0x013] = 0x6ce6bd4200d99708LLU,          [0x017] = 0x19df964c0033b23dLLU,    // 6, 134
    
    [0x018] = 0x0000008000000001LLU,    // 0
    [0x019] = 0x24ad2aa6004947ffLLU,    // 4
    [0x01a] = 0x38a678650071309eLLU,    // 8
    [0x01b] = 0x6e23d30700dc1095LLU,    // 12

    [0x01c] = 0x24ad2aa6004947ffLLU,          [0x020] = 0x0ec1293c001d7af2LLU,    // 4, 68
    [0x01d] = 0x3b4673e200766f45LLU,          [0x021] = 0x176c3cf8002eccc4LLU,    // 5, 69
    [0x01e] = 0x6ce6bd4200d99708LLU,          [0x022] = 0x1cbce51d00396b6cLLU,    // 6, 70
    [0x01f] = 0x1fb0ba0f003f519cLLU,          [0x023] = 0x2e66c102005cb64fLLU,    // 7, 71
    
    [0x024] = 0x6f621f9900de8c8fLLU,          [0x028] = 0x6609346700cbdf65LLU,    // 132, 196
    [0x025] = 0x276b191f004ec27dLLU,          [0x029] = 0x3cbc5e5b00795a5fLLU,    // 133, 197
    [0x026] = 0x19df964c0033b23dLLU,          [0x02a] = 0x54c12f7700a957ffLLU,    // 134, 198
    [0x027] = 0x1745eb64002e8034LLU,          [0x02b] = 0x0ab70035001568a5LLU,    // 135, 199
    
    [0x02c] = 0x38a678650071309eLLU,          [0x030] = 0x2bfe69ee0057e6d5LLU,    // 8, 136
    [0x02d] = 0x7044209800e05020LLU,          [0x031] = 0x23fbd7d20047e5b2LLU,    // 10, 138
    [0x02e] = 0x6e23d30700dc1095LLU,          [0x032] = 0x16ce5d81002d9154LLU,    // 12, 140
    [0x02f] = 0x0435fd7b000869e0LLU,          [0x033] = 0x3b971d8c00771070LLU,    // 14, 142
    
    [0x034] = 0x52190af100a4090aLLU,    // 16
    [0x035] = 0x5799267200af0681LLU,    // 20
    [0x036] = 0x31b9df4600635ae2LLU,    // 24
    [0x037] = 0x400e95e5007ffd25LLU,    // 28

    [0x038] = 0x38a678650071309eLLU,          [0x03c] = 0x06d300b9000da298LLU,    // 8, 72
    [0x039] = 0x20acc61100414936LLU,          [0x03d] = 0x3c6443540078aa55LLU,    // 9, 73
    [0x03a] = 0x7044209800e05020LLU,          [0x03e] = 0x58d68d4a00b180b0LLU,    // 10, 74
    [0x03b] = 0x22dd9ac40045a9c7LLU,          [0x03f] = 0x4168d8f50082b0feLLU,    // 11, 75
    
    [0x040] = 0x2bfe69ee0057e6d5LLU,          [0x044] = 0x2217813e00441df7LLU,    // 136, 200
    [0x041] = 0x21727dfe0042d443LLU,          [0x045] = 0x25b57237004b580aLLU,    // 137, 201
    [0x042] = 0x23fbd7d20047e5b2LLU,          [0x046] = 0x098f77d400131a28LLU,    // 138, 202
    [0x043] = 0x3252ff0d00648cd5LLU,          [0x047] = 0x7c8d9e6b00f8dcf7LLU,    // 139, 203
    
    [0x048] = 0x52190af100a4090aLLU,          [0x04c] = 0x1d275d3a003a4027LLU,    // 16, 144
    [0x049] = 0x7333485f00e62cf8LLU,          [0x04d] = 0x319553a3006311ddLLU,    // 18, 146
    [0x04a] = 0x5799267200af0681LLU,          [0x04e] = 0x0aa6298000154700LLU,    // 20, 148
    [0x04b] = 0x1c368c0700385efdLLU,          [0x04f] = 0x27836bb3004ef316LLU,    // 22, 150
    
    [0x050] = 0x188562400030fe82LLU,    // 32
    [0x051] = 0x6f5fa87b00de87a2LLU,    // 36
    [0x052] = 0x030356530006052bLLU,    // 40
    [0x053] = 0x0acf51ca0015993cLLU,    // 44

    [0x054] = 0x6e23d30700dc1095LLU,          [0x058] = 0x063c2c85000c753bLLU,    // 12, 76
    [0x055] = 0x71d5656800e371e1LLU,          [0x059] = 0x299faa4100532a85LLU,    // 13, 77
    [0x056] = 0x0435fd7b000869e0LLU,          [0x05a] = 0x4923c6a9009222fcLLU,    // 14, 78
    [0x057] = 0x5280bd5d00a4d83bLLU,          [0x05b] = 0x196c910b0032cc6cLLU,    // 15, 79
    
    [0x05c] = 0x16ce5d81002d9154LLU,          [0x060] = 0x54fffa2a00a9d575LLU,    // 140, 204
    [0x05d] = 0x7f6eac2c00fe9da2LLU,          [0x061] = 0x740da5f500e7e146LLU,    // 141, 205
    [0x05e] = 0x3b971d8c00771070LLU,          [0x062] = 0x7bb53fd400f72ca6LLU,    // 142, 206
    [0x05f] = 0x603dd31500c04b88LLU,          [0x063] = 0x04873ccb00090c36LLU,    // 143, 207
    
    [0x064] = 0x31b9df4600635ae2LLU,          [0x068] = 0x0671bbe9000ce03fLLU,    // 24, 152
    [0x065] = 0x291b4b2a00522209LLU,          [0x069] = 0x04f01a820009ddbdLLU,    // 26, 154
    [0x066] = 0x400e95e5007ffd25LLU,          [0x06a] = 0x0bb68f9800176744LLU,    // 28, 156
    [0x067] = 0x72eb5e6500e59d48LLU,          [0x06b] = 0x117fa6580022f68dLLU,    // 30, 158
    
    [0x06c] = 0x16b0e5a3002d5673LLU,    // 48
    [0x06d] = 0x254b462c004a83e7LLU,    // 52
    [0x06e] = 0x090f5c4e00121a31LLU,    // 56
    [0x06f] = 0x1b25c35600363df4LLU,    // 60

    [0x070] = 0x52190af100a4090aLLU,          [0x074] = 0x182e8489003050f2LLU,    // 16, 80
    [0x071] = 0x7d347f2300fa2a65LLU,          [0x075] = 0x4ac7330200956903LLU,    // 17, 81
    [0x072] = 0x7333485f00e62cf8LLU,          [0x076] = 0x6cc9ef0f00d95d7aLLU,    // 18, 82
    [0x073] = 0x623a874000c443f2LLU,          [0x077] = 0x4b758b970096c55dLLU,    // 19, 83
    
    [0x078] = 0x1d275d3a003a4027LLU,          [0x07c] = 0x7f342c8c00fe28c0LLU,    // 144, 208
    [0x079] = 0x396d24900072bd93LLU,          [0x07d] = 0x359c3c59006b1dabLLU,    // 145, 209
    [0x07a] = 0x319553a3006311ddLLU,          [0x07e] = 0x31c4a47700637067LLU,    // 146, 210
    [0x07b] = 0x33fa886e0067db14LLU,          [0x07f] = 0x5a5ca5cf00b48c1eLLU,    // 147, 211
    
    [0x080] = 0x188562400030fe82LLU,          [0x084] = 0x3f11c833007e0408LLU,    // 32, 160
    [0x081] = 0x2a5681f6005497d9LLU,          [0x085] = 0x4467811c0088accfLLU,    // 34, 162
    [0x082] = 0x6f5fa87b00de87a2LLU,          [0x086] = 0x57c61eb000af605bLLU,    // 36, 164
    [0x083] = 0x3967da3d0072b301LLU,          [0x087] = 0x28db0e9b0051a1b0LLU,    // 38, 166
    
    [0x088] = 0x37396d24006e573eLLU,    // 64
    [0x089] = 0x0ec1293c001d7af2LLU,    // 68
    [0x08a] = 0x06d300b9000da298LLU,    // 72
    [0x08b] = 0x063c2c85000c753bLLU,    // 76

    [0x08c] = 0x5799267200af0681LLU,          [0x090] = 0x48257f98009026edLLU,    // 20, 84
    [0x08d] = 0x07697957000ecf3eLLU,          [0x091] = 0x47217195008e1f53LLU,    // 21, 85
    [0x08e] = 0x1c368c0700385efdLLU,          [0x092] = 0x09b7835700136a2bLLU,    // 22, 86
    [0x08f] = 0x24f0f2980049cf6dLLU,          [0x093] = 0x11fc12f30023ef28LLU,    // 23, 87
    
    [0x094] = 0x0aa6298000154700LLU,          [0x098] = 0x613a47b100c243f3LLU,    // 148, 212
    [0x095] = 0x65d6663400cb79e2LLU,          [0x099] = 0x70e0c1c000e18914LLU,    // 149, 213
    [0x096] = 0x27836bb3004ef316LLU,          [0x09a] = 0x02855bd400050975LLU,    // 150, 214
    [0x097] = 0x29cbd9cd005382ceLLU,          [0x09b] = 0x7c5330d000f86839LLU,    // 151, 215
    
    [0x09c] = 0x030356530006052bLLU,          [0x0a0] = 0x2103e5580041f749LLU,    // 40, 168
    [0x09d] = 0x376997af006eb77bLLU,          [0x0a1] = 0x1d648c86003aba67LLU,    // 42, 170
    [0x09e] = 0x0acf51ca0015993cLLU,          [0x0a2] = 0x5dac613b00bb29edLLU,    // 44, 172
    [0x09f] = 0x3c0291680077e722LLU,          [0x0a3] = 0x3c43ed3f007869b9LLU,    // 46, 174
    
    [0x0a4] = 0x182e8489003050f2LLU,    // 80
    [0x0a5] = 0x48257f98009026edLLU,    // 84
    [0x0a6] = 0x26030e9e004bf31cLLU,    // 88
    [0x0a7] = 0x610d256800c1e9c5LLU,    // 92

    [0x0a8] = 0x31b9df4600635ae2LLU,          [0x0ac] = 0x26030e9e004bf31cLLU,    // 24, 88
    [0x0a9] = 0x3c8057d90078e270LLU,          [0x0ad] = 0x0460e4350008bf98LLU,    // 25, 89
    [0x0aa] = 0x291b4b2a00522209LLU,          [0x0ae] = 0x07109ea1000e1db5LLU,    // 26, 90
    [0x0ab] = 0x4c8c53c80098f262LLU,          [0x0af] = 0x3a91200d007504f8LLU,    // 27, 91
    
    [0x0b0] = 0x0671bbe9000ce03fLLU,          [0x0b4] = 0x7452249500e86a21LLU,    // 152, 216
    [0x0b1] = 0x0ba731c100174890LLU,          [0x0b5] = 0x053cef37000a7740LLU,    // 153, 217
    [0x0b2] = 0x04f01a820009ddbdLLU,          [0x0b6] = 0x2ee24161005dad12LLU,    // 154, 218
    [0x0b3] = 0x46d16b14008d7f6eLLU,          [0x0b7] = 0x54ae5f4300a93268LLU,    // 155, 219
    
    [0x0b8] = 0x16b0e5a3002d5673LLU,          [0x0bc] = 0x576462c100ae9d14LLU,    // 48, 176
    [0x0b9] = 0x73a3bbfb00e70da7LLU,          [0x0bd] = 0x05702e06000adda4LLU,    // 50, 178
    [0x0ba] = 0x254b462c004a83e7LLU,          [0x0be] = 0x0d80a21b001afa84LLU,    // 52, 180
    [0x0bb] = 0x33e7f0480067b5edLLU,          [0x0bf] = 0x273c7877004e6553LLU,    // 54, 182
    
    [0x0c0] = 0x7c36200c00f82e26LLU,    // 96
    [0x0c1] = 0x602a99c600c0251fLLU,    // 100
    [0x0c2] = 0x749f66e500e9047fLLU,    // 104
    [0x0c3] = 0x37a56923006f2f00LLU,    // 108

    [0x0c4] = 0x400e95e5007ffd25LLU,          [0x0c8] = 0x610d256800c1e9c5LLU,    // 28, 92
    [0x0c5] = 0x693778f500d23a57LLU,          [0x0c9] = 0x4ed30c74009d7eb0LLU,    // 29, 93
    [0x0c6] = 0x72eb5e6500e59d48LLU,          [0x0ca] = 0x6157c18f00c27ed8LLU,    // 30, 94
    [0x0c7] = 0x0f290e34001e4a88LLU,          [0x0cb] = 0x3a483b5500747353LLU,    // 31, 95
    
    [0x0cc] = 0x0bb68f9800176744LLU,          [0x0d0] = 0x1467e6650028c599LLU,    // 156, 220
    [0x0cd] = 0x2a5057ec00548b88LLU,          [0x0d1] = 0x5499ad1700a9090eLLU,    // 157, 221
    [0x0ce] = 0x117fa6580022f68dLLU,          [0x0d2] = 0x184bd5dd00308b86LLU,    // 158, 222
    [0x0cf] = 0x27fca602004fe54eLLU,          [0x0d3] = 0x6041527400c05285LLU,    // 159, 223
    
    [0x0d4] = 0x090f5c4e00121a31LLU,          [0x0d8] = 0x59cbb69400b36a88LLU,    // 56, 184
    [0x0d5] = 0x0c405d0b00187a9aLLU,          [0x0d9] = 0x348b32180068fc1fLLU,    // 58, 186
    [0x0d6] = 0x1b25c35600363df4LLU,          [0x0da] = 0x01b6d1b300036cc8LLU,    // 60, 188
    [0x0d7] = 0x160e6a04002c11cdLLU,          [0x0db] = 0x3a6210ca0074a6f1LLU,    // 62, 190
    
    [0x0dc] = 0x48cce1f00091755eLLU,    // 112
    [0x0dd] = 0x4417711800880cd7LLU,    // 116
    [0x0de] = 0x139ca61600272f7eLLU,    // 120
    [0x0df] = 0x5758e7e300ae8624LLU,    // 124

    [0x0e0] = 0x188562400030fe82LLU,          [0x0e4] = 0x7c36200c00f82e26LLU,    // 32, 96
    [0x0e1] = 0x2eac16d7005d40d8LLU,          [0x0e5] = 0x19d6c4170033a09dLLU,    // 33, 97
    [0x0e2] = 0x2a5681f6005497d9LLU,          [0x0e6] = 0x7ee2e63b00fd865cLLU,    // 34, 98
    [0x0e3] = 0x09c6350300138787LLU,          [0x0e7] = 0x0183ba6d000306b3LLU,    // 35, 99
    
    [0x0e8] = 0x3f11c833007e0408LLU,          [0x0ec] = 0x573fa59200ae53acLLU,    // 160, 224
    [0x0e9] = 0x009d93e400013ad9LLU,          [0x0ed] = 0x3f8bbeb0007ef7b8LLU,    // 161, 225
    [0x0ea] = 0x4467811c0088accfLLU,          [0x0ee] = 0x37ebc2b9006fbb90LLU,    // 162, 226
    [0x0eb] = 0x3d225759007a261eLLU,          [0x0ef] = 0x021d926200043a16LLU,    // 163, 227
    
    [0x0f0] = 0x37396d24006e573eLLU,          [0x0f4] = 0x35394d1e006a57feLLU,    // 64, 192
    [0x0f1] = 0x33078b300065f593LLU,          [0x0f5] = 0x23e31e240047b44bLLU,    // 66, 194
    [0x0f2] = 0x0ec1293c001d7af2LLU,          [0x0f6] = 0x6609346700cbdf65LLU,    // 68, 196
    [0x0f3] = 0x1cbce51d00396b6cLLU,          [0x0f7] = 0x54c12f7700a957ffLLU,    // 70, 198
    
    [0x0f8] = 0x497e62cf0092d807LLU,    // 128
    [0x0f9] = 0x6f621f9900de8c8fLLU,    // 132
    [0x0fa] = 0x2bfe69ee0057e6d5LLU,    // 136
    [0x0fb] = 0x16ce5d81002d9154LLU,    // 140

    [0x0fc] = 0x6f5fa87b00de87a2LLU,          [0x100] = 0x602a99c600c0251fLLU,    // 36, 100
    [0x0fd] = 0x3b1225ce007606c3LLU,          [0x101] = 0x37ec2a53006fbc5fLLU,    // 37, 101
    [0x0fe] = 0x3967da3d0072b301LLU,          [0x102] = 0x7898952d00f0f4dfLLU,    // 38, 102
    [0x0ff] = 0x5320bfdd00a617f0LLU,          [0x103] = 0x3406aaf70067f353LLU,    // 39, 103
    
    [0x104] = 0x57c61eb000af605bLLU,          [0x108] = 0x45fdf9b8008bd8f5LLU,    // 164, 228
    [0x105] = 0x7d18be3200f9f2f1LLU,          [0x109] = 0x6e4eff5200dc66d8LLU,    // 165, 229
    [0x106] = 0x28db0e9b0051a1b0LLU,          [0x10a] = 0x1d87a54c003b0087LLU,    // 166, 230
    [0x107] = 0x53b9e32500a749eaLLU,          [0x10b] = 0x0d2336c1001a3fdcLLU,    // 167, 231
    
    [0x10c] = 0x06d300b9000da298LLU,          [0x110] = 0x2217813e00441df7LLU,    // 72, 200
    [0x10d] = 0x58d68d4a00b180b0LLU,          [0x111] = 0x098f77d400131a28LLU,    // 74, 202
    [0x10e] = 0x063c2c85000c753bLLU,          [0x112] = 0x54fffa2a00a9d575LLU,    // 76, 204
    [0x10f] = 0x4923c6a9009222fcLLU,          [0x113] = 0x7bb53fd400f72ca6LLU,    // 78, 206
    
    [0x114] = 0x1d275d3a003a4027LLU,    // 144
    [0x115] = 0x0aa6298000154700LLU,    // 148
    [0x116] = 0x0671bbe9000ce03fLLU,    // 152
    [0x117] = 0x0bb68f9800176744LLU,    // 156

    [0x118] = 0x030356530006052bLLU,          [0x11c] = 0x749f66e500e9047fLLU,    // 40, 104
    [0x119] = 0x2769af44004ebfaaLLU,          [0x11d] = 0x458d2183008af77dLLU,    // 41, 105
    [0x11a] = 0x376997af006eb77bLLU,          [0x11e] = 0x7b1aea3f00f5f848LLU,    // 42, 106
    [0x11b] = 0x18ce8408003190a1LLU,          [0x11f] = 0x6c68e84e00d89b9dLLU,    // 43, 107
    
    [0x120] = 0x2103e5580041f749LLU,          [0x124] = 0x5dd5df9a00bb7cd5LLU,    // 168, 232
    [0x121] = 0x34c87cea00697696LLU,          [0x125] = 0x17bef726002f720fLLU,    // 169, 233
    [0x122] = 0x1d648c86003aba67LLU,          [0x126] = 0x2b92a4fe00570f81LLU,    // 170, 234
    [0x123] = 0x39b9ebc1007356fbLLU,          [0x127] = 0x772b205100ee1aacLLU,    // 171, 235
    
    [0x128] = 0x182e8489003050f2LLU,          [0x12c] = 0x7f342c8c00fe28c0LLU,    // 80, 208
    [0x129] = 0x6cc9ef0f00d95d7aLLU,          [0x12d] = 0x31c4a47700637067LLU,    // 82, 210
    [0x12a] = 0x48257f98009026edLLU,          [0x12e] = 0x613a47b100c243f3LLU,    // 84, 212
    [0x12b] = 0x09b7835700136a2bLLU,          [0x12f] = 0x02855bd400050975LLU,    // 86, 214
    
    [0x130] = 0x3f11c833007e0408LLU,    // 160
    [0x131] = 0x57c61eb000af605bLLU,    // 164
    [0x132] = 0x2103e5580041f749LLU,    // 168
    [0x133] = 0x5dac613b00bb29edLLU,    // 172

    [0x134] = 0x0acf51ca0015993cLLU,          [0x138] = 0x37a56923006f2f00LLU,    // 44, 108
    [0x135] = 0x0c630b360018bfe5LLU,          [0x139] = 0x7a2dff0600f41ee8LLU,    // 45, 109
    [0x136] = 0x3c0291680077e722LLU,          [0x13a] = 0x62df47ef00c58d21LLU,    // 46, 110
    [0x137] = 0x22aa7c7c004543a4LLU,          [0x13b] = 0x53128ed100a5fb95LLU,    // 47, 111
    
    [0x13c] = 0x5dac613b00bb29edLLU,          [0x140] = 0x0bfc34010017f26aLLU,    // 172, 236
    [0x13d] = 0x4d33fe32009a4163LLU,          [0x141] = 0x179cbd98002f2dadLLU,    // 173, 237
    [0x13e] = 0x3c43ed3f007869b9LLU,          [0x142] = 0x1f2af81f003e465bLLU,    // 174, 238
    [0x13f] = 0x4aaced7100953485LLU,          [0x143] = 0x60fe19a500c1cbb5LLU,    // 175, 239
    
    [0x144] = 0x26030e9e004bf31cLLU,          [0x148] = 0x7452249500e86a21LLU,    // 88, 216
    [0x145] = 0x07109ea1000e1db5LLU,          [0x149] = 0x2ee24161005dad12LLU,    // 90, 218
    [0x146] = 0x610d256800c1e9c5LLU,          [0x14a] = 0x1467e6650028c599LLU,    // 92, 220
    [0x147] = 0x6157c18f00c27ed8LLU,          [0x14b] = 0x184bd5dd00308b86LLU,    // 94, 222
    
    [0x14c] = 0x576462c100ae9d14LLU,    // 176
    [0x14d] = 0x0d80a21b001afa84LLU,    // 180
    [0x14e] = 0x59cbb69400b36a88LLU,    // 184
    [0x14f] = 0x01b6d1b300036cc8LLU,    // 188

    [0x150] = 0x16b0e5a3002d5673LLU,          [0x154] = 0x48cce1f00091755eLLU,    // 48, 112
    [0x151] = 0x0148a5a8000290a7LLU,          [0x155] = 0x2e229a78005c2e24LLU,    // 49, 113
    [0x152] = 0x73a3bbfb00e70da7LLU,          [0x156] = 0x6c8b185a00d8dfecLLU,    // 50, 114
    [0x153] = 0x4fd5c622009f83a2LLU,          [0x157] = 0x1e96336e003d1d1cLLU,    // 51, 115
    
    [0x158] = 0x576462c100ae9d14LLU,          [0x15c] = 0x36ee3cd8006dc103LLU,    // 176, 240
    [0x159] = 0x4ea56e0d009d238aLLU,          [0x15d] = 0x0dfe5307001bf5a7LLU,    // 177, 241
    [0x15a] = 0x05702e06000adda4LLU,          [0x15e] = 0x376aa873006eb99cLLU,    // 178, 242
    [0x15b] = 0x0d3cbca2001a72dbLLU,          [0x15f] = 0x6664021a00cc94d3LLU,    // 179, 243
    
    [0x160] = 0x7c36200c00f82e26LLU,          [0x164] = 0x573fa59200ae53acLLU,    // 96, 224
    [0x161] = 0x7ee2e63b00fd865cLLU,          [0x165] = 0x37ebc2b9006fbb90LLU,    // 98, 226
    [0x162] = 0x602a99c600c0251fLLU,          [0x166] = 0x45fdf9b8008bd8f5LLU,    // 100, 228
    [0x163] = 0x7898952d00f0f4dfLLU,          [0x167] = 0x1d87a54c003b0087LLU,    // 102, 230
    
    [0x168] = 0x35394d1e006a57feLLU,    // 192
    [0x169] = 0x6609346700cbdf65LLU,    // 196
    [0x16a] = 0x2217813e00441df7LLU,    // 200
    [0x16b] = 0x54fffa2a00a9d575LLU,    // 204

    [0x16c] = 0x254b462c004a83e7LLU,          [0x170] = 0x4417711800880cd7LLU,    // 52, 116
    [0x16d] = 0x2a4028e000546b32LLU,          [0x171] = 0x19aa81070033482dLLU,    // 53, 117
    [0x16e] = 0x33e7f0480067b5edLLU,          [0x172] = 0x23d6cf1000479bb3LLU,    // 54, 118
    [0x16f] = 0x4f7fa59a009ed78cLLU,          [0x173] = 0x4a5297dc00948007LLU,    // 55, 119
    
    [0x174] = 0x0d80a21b001afa84LLU,          [0x178] = 0x23db13210047a439LLU,    // 180, 244
    [0x175] = 0x19f96ec20033e5e1LLU,          [0x179] = 0x264949ac004c7f6fLLU,    // 181, 245
    [0x176] = 0x273c7877004e6553LLU,          [0x17a] = 0x50aa5cc700a12c65LLU,    // 182, 246
    [0x177] = 0x51fd06f000a3d110LLU,          [0x17b] = 0x53a72ff800a7248dLLU,    // 183, 247
    
    [0x17c] = 0x749f66e500e9047fLLU,          [0x180] = 0x5dd5df9a00bb7cd5LLU,    // 104, 232
    [0x17d] = 0x7b1aea3f00f5f848LLU,          [0x181] = 0x2b92a4fe00570f81LLU,    // 106, 234
    [0x17e] = 0x37a56923006f2f00LLU,          [0x182] = 0x0bfc34010017f26aLLU,    // 108, 236
    [0x17f] = 0x62df47ef00c58d21LLU,          [0x183] = 0x1f2af81f003e465bLLU,    // 110, 238
    
    [0x184] = 0x7f342c8c00fe28c0LLU,    // 208
    [0x185] = 0x613a47b100c243f3LLU,    // 212
    [0x186] = 0x7452249500e86a21LLU,    // 216
    [0x187] = 0x1467e6650028c599LLU,    // 220

    [0x188] = 0x090f5c4e00121a31LLU,          [0x18c] = 0x139ca61600272f7eLLU,    // 56, 120
    [0x189] = 0x091c809700123473LLU,          [0x18d] = 0x258072f7004aee26LLU,    // 57, 121
    [0x18a] = 0x0c405d0b00187a9aLLU,          [0x18e] = 0x51f04d4100a3b7a3LLU,    // 58, 122
    [0x18b] = 0x4ff675cd009fc4f1LLU,          [0x18f] = 0x3e050984007beb11LLU,    // 59, 123
    
    [0x190] = 0x59cbb69400b36a88LLU,          [0x194] = 0x6de9d00600db9cacLLU,    // 184, 248
    [0x191] = 0x226a3b6c0044c342LLU,          [0x195] = 0x7884bf3700f0cd3dLLU,    // 185, 249
    [0x192] = 0x348b32180068fc1fLLU,          [0x196] = 0x0e0a0bf5001c0d13LLU,    // 186, 250
    [0x193] = 0x5253d72300a47e85LLU,          [0x197] = 0x5fa76ffc00bf1f0dLLU,    // 187, 251
    
    [0x198] = 0x48cce1f00091755eLLU,          [0x19c] = 0x36ee3cd8006dc103LLU,    // 112, 240
    [0x199] = 0x6c8b185a00d8dfecLLU,          [0x19d] = 0x376aa873006eb99cLLU,    // 114, 242
    [0x19a] = 0x4417711800880cd7LLU,          [0x19e] = 0x23db13210047a439LLU,    // 116, 244
    [0x19b] = 0x23d6cf1000479bb3LLU,          [0x19f] = 0x50aa5cc700a12c65LLU,    // 118, 246
    
    [0x1a0] = 0x573fa59200ae53acLLU,    // 224
    [0x1a1] = 0x45fdf9b8008bd8f5LLU,    // 228
    [0x1a2] = 0x5dd5df9a00bb7cd5LLU,    // 232
    [0x1a3] = 0x0bfc34010017f26aLLU,    // 236

    [0x1a4] = 0x1b25c35600363df4LLU,          [0x1a8] = 0x5758e7e300ae8624LLU,    // 60, 124
    [0x1a5] = 0x261f9dc1004c2c2cLLU,          [0x1a9] = 0x435595a200868981LLU,    // 61, 125
    [0x1a6] = 0x160e6a04002c11cdLLU,          [0x1aa] = 0x4b6e78d30096b73bLLU,    // 62, 126
    [0x1a7] = 0x18c3f3e400317b86LLU,          [0x1ab] = 0x6366703900c69b2eLLU,    // 63, 127
    
    [0x1ac] = 0x01b6d1b300036cc8LLU,          [0x1b0] = 0x2654a984004c9629LLU,    // 188, 252
    [0x1ad] = 0x3038746d006058cdLLU,          [0x1b1] = 0x6406a3c500c7db45LLU,    // 189, 253
    [0x1ae] = 0x3a6210ca0074a6f1LLU,          [0x1b2] = 0x2e2c315e005c414dLLU,    // 190, 254
    [0x1af] = 0x1b4a80850036875cLLU,          [0x1b3] = 0x26cc86fb004d85a8LLU,    // 191, 255
    
    [0x1b4] = 0x139ca61600272f7eLLU,          [0x1b8] = 0x6de9d00600db9cacLLU,    // 120, 248
    [0x1b5] = 0x51f04d4100a3b7a3LLU,          [0x1b9] = 0x0e0a0bf5001c0d13LLU,    // 122, 250
    [0x1b6] = 0x5758e7e300ae8624LLU,          [0x1ba] = 0x2654a984004c9629LLU,    // 124, 252
    [0x1b7] = 0x4b6e78d30096b73bLLU,          [0x1bb] = 0x2e2c315e005c414dLLU,    // 126, 254
    
    [0x1bc] = 0x36ee3cd8006dc103LLU,    // 240
    [0x1bd] = 0x23db13210047a439LLU,    // 244
    [0x1be] = 0x6de9d00600db9cacLLU,    // 248
    [0x1bf] = 0x2654a984004c9629LLU,    // 252

    [0x1c0] = 0x0000008000000001LLU,          [0x1d0] = 0x497e62cf0092d807LLU,
    [0x1c1] = 0x38a678650071309eLLU,          [0x1d1] = 0x2bfe69ee0057e6d5LLU,
    [0x1c2] = 0x52190af100a4090aLLU,          [0x1d2] = 0x1d275d3a003a4027LLU,
    [0x1c3] = 0x31b9df4600635ae2LLU,          [0x1d3] = 0x0671bbe9000ce03fLLU,

    [0x1c4] = 0x188562400030fe82LLU,          [0x1d4] = 0x3f11c833007e0408LLU,
    [0x1c5] = 0x030356530006052bLLU,          [0x1d5] = 0x2103e5580041f749LLU,
    [0x1c6] = 0x16b0e5a3002d5673LLU,          [0x1d6] = 0x576462c100ae9d14LLU,
    [0x1c7] = 0x090f5c4e00121a31LLU,          [0x1d7] = 0x59cbb69400b36a88LLU,

    [0x1c8] = 0x37396d24006e573eLLU,          [0x1d8] = 0x35394d1e006a57feLLU,
    [0x1c9] = 0x06d300b9000da298LLU,          [0x1d9] = 0x2217813e00441df7LLU,
    [0x1ca] = 0x182e8489003050f2LLU,          [0x1da] = 0x7f342c8c00fe28c0LLU,
    [0x1cb] = 0x26030e9e004bf31cLLU,          [0x1db] = 0x7452249500e86a21LLU,

    [0x1cc] = 0x7c36200c00f82e26LLU,          [0x1dc] = 0x573fa59200ae53acLLU,
    [0x1cd] = 0x749f66e500e9047fLLU,          [0x1dd] = 0x5dd5df9a00bb7cd5LLU,
    [0x1ce] = 0x48cce1f00091755eLLU,          [0x1de] = 0x36ee3cd8006dc103LLU,
    [0x1cf] = 0x139ca61600272f7eLLU,          [0x1df] = 0x6de9d00600db9cacLLU,
};

static const uint64_t args_w_Wh_16760833_512_11680345_32_16_8_4_2[0x18] = {

    // 32-NTT: 11680345^i, Jump 16
    [0x0] = 0x0000008000000001LLU,       [0x8] = 0x36819d31006ce7faLLU,
    [0x1] = 0x4911c3280091fefeLLU,       [0x9] = 0x37331e10006e4aa3LLU,
    [0x2] = 0x28c05a6e00516c55LLU,       [0xa] = 0x03c9dff4000791dbLLU,
    [0x3] = 0x00cbd37400019741LLU,       [0xb] = 0x67d17b7700cf6f0fLLU,
    [0x4] = 0x4ac6b2e200956803LLU,       [0xc] = 0x48c692dc009168c3LLU,
    [0x5] = 0x289b9d3f005122edLLU,       [0xd] = 0x694f1a5d00d2698eLLU,
    [0x6] = 0x40ee37cd0081bbf9LLU,       [0xe] = 0x677a9dc000cec17fLLU,
    [0x7] = 0x62d8a2c600c57fdaLLU,       [0xf] = 0x2de6f50f005bb6f7LLU,

    // 16-NTT: 11680345^i, Jump 32
    [0x10] = 0x0000008000000001LLU,      [0x14] = 0x36819d31006ce7faLLU,
    [0x11] = 0x28c05a6e00516c55LLU,      [0x15] = 0x03c9dff4000791dbLLU,
    [0x12] = 0x4ac6b2e200956803LLU,      [0x16] = 0x48c692dc009168c3LLU,
    [0x13] = 0x40ee37cd0081bbf9LLU,      [0x17] = 0x677a9dc000cec17fLLU,

    // 8_4_2-NTT: there's no reload on twiddle factors (generated by trn1/2)
};

static const uint64_t args_w_Wh_16760833_512_11680345[512] = {

    // 11680345^i, Jump 1
    [0] = 0x0000008000000001LLU,
    [1] = 0x5933790500b23a59LLU,
    [2] = 0x51d3cea200a37eb4LLU,
    [3] = 0x1bf95c3b0037e4bcLLU,
    [4] = 0x59ab567c00b329d8LLU,
    [5] = 0x205890040040a0f4LLU,
    [6] = 0x71f5f40b00e3b2eeLLU,
    [7] = 0x077b40c9000ef2c4LLU,
    [8] = 0x12162ffa00242355LLU,
    [9] = 0x2c58d00800589b74LLU,
    [10] = 0x2f55a339005e939cLLU,
    [11] = 0x59b6b65400b34092LLU,
    [12] = 0x5c24ecdf00b81bc8LLU,
    [13] = 0x199bfde600332b2eLLU,
    [14] = 0x4895578d00910665LLU,
    [15] = 0x7201acf900e3ca5aLLU,
    [16] = 0x4911c3280091fefeLLU,
    [17] = 0x1f01e65b003df44cLLU,
    [18] = 0x60d507e100c179a6LLU,
    [19] = 0x6863426800d09254LLU,
    [20] = 0x7403cbff00e7cd97LLU,
    [21] = 0x08d4dfaf0011a555LLU,
    [22] = 0x546d5b0200a8b080LLU,
    [23] = 0x684108da00d04df2LLU,
    [24] = 0x222a20660044432cLLU,
    [25] = 0x72dcc93f00e58025LLU,
    [26] = 0x62785ab400c4bf7aLLU,
    [27] = 0x11b100ae00235929LLU,
    [28] = 0x3a0206480073e70cLLU,
    [29] = 0x7de26d9e00fb85ebLLU,
    [30] = 0x48143d4700900471LLU,
    [31] = 0x407441500080c849LLU,
    [32] = 0x28c05a6e00516c55LLU,
    [33] = 0x1fbead8c003f6d7cLLU,
    [34] = 0x67b42a2300cf347bLLU,
    [35] = 0x2b6652e90056b6f3LLU,
    [36] = 0x6b98199b00d6fa68LLU,
    [37] = 0x2b51a0bd00568d99LLU,
    [38] = 0x511dbe9f00a212efLLU,
    [39] = 0x7ac310c900f548c1LLU,
    [40] = 0x0baddb6b001755e0LLU,
    [41] = 0x03accf30000757c8LLU,
    [42] = 0x7d7aa42c00fab68cLLU,
    [43] = 0x0f1f3e40001e36edLLU,
    [44] = 0x1ec5b84f003d7c0eLLU,
    [45] = 0x25a35a31004b33e3LLU,
    [46] = 0x4e3b5b89009c4f9aLLU,
    [47] = 0x4a63c3a70094a256LLU,
    [48] = 0x00cbd37400019741LLU,
    [49] = 0x7b78c33500f6b3cbLLU,
    [50] = 0x044ac02c0008935bLLU,
    [51] = 0x0bf25a0b0017debbLLU,
    [52] = 0x2b0005d60055ea8cLLU,
    [53] = 0x037261950006e30aLLU,
    [54] = 0x7670882c00eca5d9LLU,
    [55] = 0x5a4a8dc900b467f7LLU,
    [56] = 0x5de87ec200bba20aLLU,
    [57] = 0x7548ffcb00ea575cLLU,
    [58] = 0x2b3ed08900566802LLU,
    [59] = 0x4343a1a5008665a2LLU,
    [60] = 0x19f6cb990033e09cLLU,
    [61] = 0x0143ea7900028733LLU,
    [62] = 0x5c1ce1dc00b80bb6LLU,
    [63] = 0x1c6d2aae0038cc1fLLU,
    [64] = 0x4ac6b2e200956803LLU,
    [65] = 0x64b57f7b00c938a5LLU,
    [66] = 0x459def36008b1910LLU,
    [67] = 0x4fc78b93009f6734LLU,
    [68] = 0x7e492e4d00fc5339LLU,
    [69] = 0x2dac28dd005b417cLLU,
    [70] = 0x4b74cde80096c3e2LLU,
    [71] = 0x5d95c49400bafcbfLLU,
    [72] = 0x2634496c004c5579LLU,
    [73] = 0x2e02f910005beef1LLU,
    [74] = 0x58c3878900b15aaeLLU,
    [75] = 0x6606913e00cbda20LLU,
    [76] = 0x727f5de500e4c57dLLU,
    [77] = 0x72c3435e00e54d26LLU,
    [78] = 0x7a8fd1fa00f4e25dLLU,
    [79] = 0x315a91f300629c77LLU,
    [80] = 0x289b9d3f005122edLLU,
    [81] = 0x3553128f006a8b7cLLU,
    [82] = 0x43bc12c100875648LLU,
    [83] = 0x32cc01ce00657e9eLLU,
    [84] = 0x22539ec500449614LLU,
    [85] = 0x4646143f008c6906LLU,
    [86] = 0x629b737a00c5059aLLU,
    [87] = 0x4b3783160096496bLLU,
    [88] = 0x5efc1aa800bdc8b8LLU,
    [89] = 0x2c461cdb00587617LLU,
    [90] = 0x5724f16500ae1e51LLU,
    [91] = 0x02e741ce0005cd10LLU,
    [92] = 0x2839e15000505fa6LLU,
    [93] = 0x42dda8a7008599e3LLU,
    [94] = 0x3b987ee400771332LLU,
    [95] = 0x7f626c1c00fe8528LLU,
    [96] = 0x40ee37cd0081bbf9LLU,
    [97] = 0x580359fe00afdab3LLU,
    [98] = 0x6e8059a800dcc974LLU,
    [99] = 0x55afa81400ab3479LLU,
    [100] = 0x7449706800e858bdLLU,
    [101] = 0x392e94ec00724093LLU,
    [102] = 0x7b0fe57e00f5e244LLU,
    [103] = 0x7458ce3f00e87771LLU,
    [104] = 0x798e441700f2dfc2LLU,
    [105] = 0x5634263300ac3d33LLU,
    [106] = 0x587c944d00b0ccebLLU,
    [107] = 0x1a2999cc0034461fLLU,
    [108] = 0x7559d68000ea7901LLU,
    [109] = 0x4c0577920097e4edLLU,
    [110] = 0x4e6aac5d009cae24LLU,
    [111] = 0x4692db70008d026eLLU,
    [112] = 0x62d8a2c600c57fdaLLU,
    [113] = 0x1fc22ceb003f7479LLU,
    [114] = 0x4468e2740088af91LLU,
    [115] = 0x009153d40001225fLLU,
    [116] = 0x6931a27f00d22eadLLU,
    [117] = 0x4dad00f3009b332cLLU,
    [118] = 0x5c04282e00b7da4fLLU,
    [119] = 0x5e8d820200bcebbeLLU,
    [120] = 0x5401961200a7d92cLLU,
    [121] = 0x68ba149c00d13fcdLLU,
    [122] = 0x662069b400cc0dc4LLU,
    [123] = 0x5894e6e100b0fd84LLU,
    [124] = 0x109de06700213372LLU,
    [125] = 0x13aead1800275383LLU,
    [126] = 0x4558aae5008a8eaaLLU,
    [127] = 0x06089a20000c0e30LLU,
    [128] = 0x36819d31006ce7faLLU,
    [129] = 0x1c998fc7003924d3LLU,
    [130] = 0x3491872d006908c6LLU,
    [131] = 0x3caa6a5e00793680LLU,
    [132] = 0x28a7181d005139ddLLU,
    [133] = 0x41faf67c0083d4f0LLU,
    [134] = 0x2e0fb2bf005c085eLLU,
    [135] = 0x5a7f8d0900b4d1dbLLU,
    [136] = 0x6c6359ea00d89083LLU,
    [137] = 0x35ad6824006b3ffaLLU,
    [138] = 0x5c2930f000b8244eLLU,
    [139] = 0x66557ef900cc77d4LLU,
    [140] = 0x3be88ee80077b32aLLU,
    [141] = 0x6169cc9200c2a2e5LLU,
    [142] = 0x1374e7a60026e015LLU,
    [143] = 0x51dd658800a391ddLLU,
    [144] = 0x37331e10006e4aa3LLU,
    [145] = 0x2ced712f0059c46cLLU,
    [146] = 0x1d20b811003a32e0LLU,
    [147] = 0x05d200fa000ba119LLU,
    [148] = 0x485a96dd00909101LLU,
    [149] = 0x139717b200272464LLU,
    [150] = 0x04e515c10009c7b9LLU,
    [151] = 0x3a72de7d0074c884LLU,
    [152] = 0x0b60991b0016bb82LLU,
    [153] = 0x4bf955090097ccaeLLU,
    [154] = 0x07676ad3000ecb22LLU,
    [155] = 0x4813d5ad009003a2LLU,
    [156] = 0x1fd5663a003f9ae2LLU,
    [157] = 0x7e7c459300fcb94eLLU,
    [158] = 0x011d19c5000239a5LLU,
    [159] = 0x66293be900cc1f64LLU,
    [160] = 0x03c9dff4000791dbLLU,
    [161] = 0x45b7c4ab008b4caeLLU,
    [162] = 0x1ea83e71003d4129LLU,
    [163] = 0x312cf38c00624151LLU,
    [164] = 0x1ef2da98003dd63cLLU,
    [165] = 0x456edff3008abb09LLU,
    [166] = 0x78ef615f00f1a24cLLU,
    [167] = 0x7b9f1bcb00f70069LLU,
    [168] = 0x59fcf16200b3cce5LLU,
    [169] = 0x6e03ed0d00dbd0d9LLU,
    [170] = 0x76487ca900ec55d6LLU,
    [171] = 0x38de8e6b0071a0aeLLU,
    [172] = 0x37da8068006f9914LLU,
    [173] = 0x348a74690068faa4LLU,
    [174] = 0x133610f100266287LLU,
    [175] = 0x3538ccfe006a56feLLU,
    [176] = 0x67d17b7700cf6f0fLLU,
    [177] = 0x66936ef500ccf395LLU,
    [178] = 0x36dc3957006d9d05LLU,
    [179] = 0x566055bf00ac957cLLU,
    [180] = 0x79c3d37b00f34ac6LLU,
    [181] = 0x3e97270b007d0f03LLU,
    [182] = 0x272972b6004e3f51LLU,
    [183] = 0x439bbcac008715acLLU,
    [184] = 0x792cff4700f21d69LLU,
    [185] = 0x51993efe00a309b2LLU,
    [186] = 0x63431ae300c65495LLU,
    [187] = 0x6893c30800d0f33dLLU,
    [188] = 0x713ed6c400e2450fLLU,
    [189] = 0x7018a0b800dff936LLU,
    [190] = 0x4cf874d00099ca6eLLU,
    [191] = 0x45a13b09008b1fa6LLU,
    [192] = 0x48c692dc009168c3LLU,
    [193] = 0x673c0c1c00ce447bLLU,
    [194] = 0x69f195fc00d3ae34LLU,
    [195] = 0x59e0623f00b393d5LLU,
    [196] = 0x64da3caa00c9820dLLU,
    [197] = 0x30098a33005ffb10LLU,
    [198] = 0x73bfa2f500e74567LLU,
    [199] = 0x76e37f6900ed8b8eLLU,
    [200] = 0x76f0a3b200eda5d0LLU,
    [201] = 0x30805a660060e875LLU,
    [202] = 0x4c180fb800980a14LLU,
    [203] = 0x55bfd72000ab54cfLLU,
    [204] = 0x5ab4b9d400b53c1aLLU,
    [205] = 0x302a39de00603c5fLLU,
    [206] = 0x0c5c44050018b25aLLU,
    [207] = 0x7eb75a5800fd2f5aLLU,
    [208] = 0x694f1a5d00d2698eLLU,
    [209] = 0x5d55838400ba7c5dLLU,
    [210] = 0x43fd6e980087d8dfLLU,
    [211] = 0x739cf4ca00e7001cLLU,
    [212] = 0x7530ae3600ea26c5LLU,
    [213] = 0x67317bf800ce2f60LLU,
    [214] = 0x4896685100910886LLU,
    [215] = 0x589650bc00b10057LLU,
    [216] = 0x7cfca9ad00f9bad6LLU,
    [217] = 0x2cdf40230059a811LLU,
    [218] = 0x469825c3008d0d00LLU,
    [219] = 0x44edda320089b93eLLU,
    [220] = 0x10a057850021385fLLU,
    [221] = 0x7639cafd00ec387aLLU,
    [222] = 0x55a97e0a00ab2828LLU,
    [223] = 0x5153e92900a27f29LLU,
    [224] = 0x677a9dc000cec17fLLU,
    [225] = 0x70d6f1cc00e17579LLU,
    [226] = 0x0d14a19b001a22b9LLU,
    [227] = 0x16c8870b002d85aaLLU,
    [228] = 0x3ff16a1b007fc2dcLLU,
    [229] = 0x3373ac380066cd9fLLU,
    [230] = 0x56e4b4d600ad9df8LLU,
    [231] = 0x437fa8270086dd91LLU,
    [232] = 0x4e4620ba009c651fLLU,
    [233] = 0x5b0f0d6800b5f094LLU,
    [234] = 0x63c973f900c76104LLU,
    [235] = 0x789686a900f0f0c3LLU,
    [236] = 0x2866d98e0050b980LLU,
    [237] = 0x1dc578c0003b7c0fLLU,
    [238] = 0x0cccb7a100199309LLU,
    [239] = 0x02cb80dd0005959cLLU,
    [240] = 0x2de6f50f005bb6f7LLU,
    [241] = 0x2d7f42a3005ae7c6LLU,
    [242] = 0x7bca028500f75621LLU,
    [243] = 0x0e2a9a98001c4e20LLU,
    [244] = 0x11dc2cf90023af6cLLU,
    [245] = 0x5d22653c00ba163aLLU,
    [246] = 0x0fbbdf68001f6fe1LLU,
    [247] = 0x5f5339ef00be76cbLLU,
    [248] = 0x4759879b008e8f63LLU,
    [249] = 0x604f45f100c06e65LLU,
    [250] = 0x131942be002628f9LLU,
    [251] = 0x44b98c1e008950bcLLU,
    [252] = 0x5b52d55a00b67802LLU,
    [253] = 0x5cb91e6b00b943e1LLU,
    [254] = 0x5390a75600a6f787LLU,
    [255] = 0x2d2fa33c005a48afLLU,

    // 11680345^i, Jump 2
    [256] = 0x0000008000000001LLU,
    [257] = 0x51d3cea200a37eb4LLU,
    [258] = 0x59ab567c00b329d8LLU,
    [259] = 0x71f5f40b00e3b2eeLLU,
    [260] = 0x12162ffa00242355LLU,
    [261] = 0x2f55a339005e939cLLU,
    [262] = 0x5c24ecdf00b81bc8LLU,
    [263] = 0x4895578d00910665LLU,
    [264] = 0x4911c3280091fefeLLU,
    [265] = 0x60d507e100c179a6LLU,
    [266] = 0x7403cbff00e7cd97LLU,
    [267] = 0x546d5b0200a8b080LLU,
    [268] = 0x222a20660044432cLLU,
    [269] = 0x62785ab400c4bf7aLLU,
    [270] = 0x3a0206480073e70cLLU,
    [271] = 0x48143d4700900471LLU,
    [272] = 0x28c05a6e00516c55LLU,
    [273] = 0x67b42a2300cf347bLLU,
    [274] = 0x6b98199b00d6fa68LLU,
    [275] = 0x511dbe9f00a212efLLU,
    [276] = 0x0baddb6b001755e0LLU,
    [277] = 0x7d7aa42c00fab68cLLU,
    [278] = 0x1ec5b84f003d7c0eLLU,
    [279] = 0x4e3b5b89009c4f9aLLU,
    [280] = 0x00cbd37400019741LLU,
    [281] = 0x044ac02c0008935bLLU,
    [282] = 0x2b0005d60055ea8cLLU,
    [283] = 0x7670882c00eca5d9LLU,
    [284] = 0x5de87ec200bba20aLLU,
    [285] = 0x2b3ed08900566802LLU,
    [286] = 0x19f6cb990033e09cLLU,
    [287] = 0x5c1ce1dc00b80bb6LLU,
    [288] = 0x4ac6b2e200956803LLU,
    [289] = 0x459def36008b1910LLU,
    [290] = 0x7e492e4d00fc5339LLU,
    [291] = 0x4b74cde80096c3e2LLU,
    [292] = 0x2634496c004c5579LLU,
    [293] = 0x58c3878900b15aaeLLU,
    [294] = 0x727f5de500e4c57dLLU,
    [295] = 0x7a8fd1fa00f4e25dLLU,
    [296] = 0x289b9d3f005122edLLU,
    [297] = 0x43bc12c100875648LLU,
    [298] = 0x22539ec500449614LLU,
    [299] = 0x629b737a00c5059aLLU,
    [300] = 0x5efc1aa800bdc8b8LLU,
    [301] = 0x5724f16500ae1e51LLU,
    [302] = 0x2839e15000505fa6LLU,
    [303] = 0x3b987ee400771332LLU,
    [304] = 0x40ee37cd0081bbf9LLU,
    [305] = 0x6e8059a800dcc974LLU,
    [306] = 0x7449706800e858bdLLU,
    [307] = 0x7b0fe57e00f5e244LLU,
    [308] = 0x798e441700f2dfc2LLU,
    [309] = 0x587c944d00b0ccebLLU,
    [310] = 0x7559d68000ea7901LLU,
    [311] = 0x4e6aac5d009cae24LLU,
    [312] = 0x62d8a2c600c57fdaLLU,
    [313] = 0x4468e2740088af91LLU,
    [314] = 0x6931a27f00d22eadLLU,
    [315] = 0x5c04282e00b7da4fLLU,
    [316] = 0x5401961200a7d92cLLU,
    [317] = 0x662069b400cc0dc4LLU,
    [318] = 0x109de06700213372LLU,
    [319] = 0x4558aae5008a8eaaLLU,
    [320] = 0x36819d31006ce7faLLU,
    [321] = 0x3491872d006908c6LLU,
    [322] = 0x28a7181d005139ddLLU,
    [323] = 0x2e0fb2bf005c085eLLU,
    [324] = 0x6c6359ea00d89083LLU,
    [325] = 0x5c2930f000b8244eLLU,
    [326] = 0x3be88ee80077b32aLLU,
    [327] = 0x1374e7a60026e015LLU,
    [328] = 0x37331e10006e4aa3LLU,
    [329] = 0x1d20b811003a32e0LLU,
    [330] = 0x485a96dd00909101LLU,
    [331] = 0x04e515c10009c7b9LLU,
    [332] = 0x0b60991b0016bb82LLU,
    [333] = 0x07676ad3000ecb22LLU,
    [334] = 0x1fd5663a003f9ae2LLU,
    [335] = 0x011d19c5000239a5LLU,
    [336] = 0x03c9dff4000791dbLLU,
    [337] = 0x1ea83e71003d4129LLU,
    [338] = 0x1ef2da98003dd63cLLU,
    [339] = 0x78ef615f00f1a24cLLU,
    [340] = 0x59fcf16200b3cce5LLU,
    [341] = 0x76487ca900ec55d6LLU,
    [342] = 0x37da8068006f9914LLU,
    [343] = 0x133610f100266287LLU,
    [344] = 0x67d17b7700cf6f0fLLU,
    [345] = 0x36dc3957006d9d05LLU,
    [346] = 0x79c3d37b00f34ac6LLU,
    [347] = 0x272972b6004e3f51LLU,
    [348] = 0x792cff4700f21d69LLU,
    [349] = 0x63431ae300c65495LLU,
    [350] = 0x713ed6c400e2450fLLU,
    [351] = 0x4cf874d00099ca6eLLU,
    [352] = 0x48c692dc009168c3LLU,
    [353] = 0x69f195fc00d3ae34LLU,
    [354] = 0x64da3caa00c9820dLLU,
    [355] = 0x73bfa2f500e74567LLU,
    [356] = 0x76f0a3b200eda5d0LLU,
    [357] = 0x4c180fb800980a14LLU,
    [358] = 0x5ab4b9d400b53c1aLLU,
    [359] = 0x0c5c44050018b25aLLU,
    [360] = 0x694f1a5d00d2698eLLU,
    [361] = 0x43fd6e980087d8dfLLU,
    [362] = 0x7530ae3600ea26c5LLU,
    [363] = 0x4896685100910886LLU,
    [364] = 0x7cfca9ad00f9bad6LLU,
    [365] = 0x469825c3008d0d00LLU,
    [366] = 0x10a057850021385fLLU,
    [367] = 0x55a97e0a00ab2828LLU,
    [368] = 0x677a9dc000cec17fLLU,
    [369] = 0x0d14a19b001a22b9LLU,
    [370] = 0x3ff16a1b007fc2dcLLU,
    [371] = 0x56e4b4d600ad9df8LLU,
    [372] = 0x4e4620ba009c651fLLU,
    [373] = 0x63c973f900c76104LLU,
    [374] = 0x2866d98e0050b980LLU,
    [375] = 0x0cccb7a100199309LLU,
    [376] = 0x2de6f50f005bb6f7LLU,
    [377] = 0x7bca028500f75621LLU,
    [378] = 0x11dc2cf90023af6cLLU,
    [379] = 0x0fbbdf68001f6fe1LLU,
    [380] = 0x4759879b008e8f63LLU,
    [381] = 0x131942be002628f9LLU,
    [382] = 0x5b52d55a00b67802LLU,
    [383] = 0x5390a75600a6f787LLU,

    // 11680345^i, Jump 4
    [384] = 0x0000008000000001LLU,
    [385] = 0x59ab567c00b329d8LLU,
    [386] = 0x12162ffa00242355LLU,
    [387] = 0x5c24ecdf00b81bc8LLU,
    [388] = 0x4911c3280091fefeLLU,
    [389] = 0x7403cbff00e7cd97LLU,
    [390] = 0x222a20660044432cLLU,
    [391] = 0x3a0206480073e70cLLU,
    [392] = 0x28c05a6e00516c55LLU,
    [393] = 0x6b98199b00d6fa68LLU,
    [394] = 0x0baddb6b001755e0LLU,
    [395] = 0x1ec5b84f003d7c0eLLU,
    [396] = 0x00cbd37400019741LLU,
    [397] = 0x2b0005d60055ea8cLLU,
    [398] = 0x5de87ec200bba20aLLU,
    [399] = 0x19f6cb990033e09cLLU,
    [400] = 0x4ac6b2e200956803LLU,
    [401] = 0x7e492e4d00fc5339LLU,
    [402] = 0x2634496c004c5579LLU,
    [403] = 0x727f5de500e4c57dLLU,
    [404] = 0x289b9d3f005122edLLU,
    [405] = 0x22539ec500449614LLU,
    [406] = 0x5efc1aa800bdc8b8LLU,
    [407] = 0x2839e15000505fa6LLU,
    [408] = 0x40ee37cd0081bbf9LLU,
    [409] = 0x7449706800e858bdLLU,
    [410] = 0x798e441700f2dfc2LLU,
    [411] = 0x7559d68000ea7901LLU,
    [412] = 0x62d8a2c600c57fdaLLU,
    [413] = 0x6931a27f00d22eadLLU,
    [414] = 0x5401961200a7d92cLLU,
    [415] = 0x109de06700213372LLU,
    [416] = 0x36819d31006ce7faLLU,
    [417] = 0x28a7181d005139ddLLU,
    [418] = 0x6c6359ea00d89083LLU,
    [419] = 0x3be88ee80077b32aLLU,
    [420] = 0x37331e10006e4aa3LLU,
    [421] = 0x485a96dd00909101LLU,
    [422] = 0x0b60991b0016bb82LLU,
    [423] = 0x1fd5663a003f9ae2LLU,
    [424] = 0x03c9dff4000791dbLLU,
    [425] = 0x1ef2da98003dd63cLLU,
    [426] = 0x59fcf16200b3cce5LLU,
    [427] = 0x37da8068006f9914LLU,
    [428] = 0x67d17b7700cf6f0fLLU,
    [429] = 0x79c3d37b00f34ac6LLU,
    [430] = 0x792cff4700f21d69LLU,
    [431] = 0x713ed6c400e2450fLLU,
    [432] = 0x48c692dc009168c3LLU,
    [433] = 0x64da3caa00c9820dLLU,
    [434] = 0x76f0a3b200eda5d0LLU,
    [435] = 0x5ab4b9d400b53c1aLLU,
    [436] = 0x694f1a5d00d2698eLLU,
    [437] = 0x7530ae3600ea26c5LLU,
    [438] = 0x7cfca9ad00f9bad6LLU,
    [439] = 0x10a057850021385fLLU,
    [440] = 0x677a9dc000cec17fLLU,
    [441] = 0x3ff16a1b007fc2dcLLU,
    [442] = 0x4e4620ba009c651fLLU,
    [443] = 0x2866d98e0050b980LLU,
    [444] = 0x2de6f50f005bb6f7LLU,
    [445] = 0x11dc2cf90023af6cLLU,
    [446] = 0x4759879b008e8f63LLU,
    [447] = 0x5b52d55a00b67802LLU,

    // 11680345^i, Jump 8
    [448] = 0x0000008000000001LLU,
    [449] = 0x12162ffa00242355LLU,
    [450] = 0x4911c3280091fefeLLU,
    [451] = 0x222a20660044432cLLU,
    [452] = 0x28c05a6e00516c55LLU,
    [453] = 0x0baddb6b001755e0LLU,
    [454] = 0x00cbd37400019741LLU,
    [455] = 0x5de87ec200bba20aLLU,
    [456] = 0x4ac6b2e200956803LLU,
    [457] = 0x2634496c004c5579LLU,
    [458] = 0x289b9d3f005122edLLU,
    [459] = 0x5efc1aa800bdc8b8LLU,
    [460] = 0x40ee37cd0081bbf9LLU,
    [461] = 0x798e441700f2dfc2LLU,
    [462] = 0x62d8a2c600c57fdaLLU,
    [463] = 0x5401961200a7d92cLLU,
    [464] = 0x36819d31006ce7faLLU,
    [465] = 0x6c6359ea00d89083LLU,
    [466] = 0x37331e10006e4aa3LLU,
    [467] = 0x0b60991b0016bb82LLU,
    [468] = 0x03c9dff4000791dbLLU,
    [469] = 0x59fcf16200b3cce5LLU,
    [470] = 0x67d17b7700cf6f0fLLU,
    [471] = 0x792cff4700f21d69LLU,
    [472] = 0x48c692dc009168c3LLU,
    [473] = 0x76f0a3b200eda5d0LLU,
    [474] = 0x694f1a5d00d2698eLLU,
    [475] = 0x7cfca9ad00f9bad6LLU,
    [476] = 0x677a9dc000cec17fLLU,
    [477] = 0x4e4620ba009c651fLLU,
    [478] = 0x2de6f50f005bb6f7LLU,
    [479] = 0x4759879b008e8f63LLU,

    // 11680345^i, Jump 16
    [480] = 0x0000008000000001LLU,
    [481] = 0x4911c3280091fefeLLU,
    [482] = 0x28c05a6e00516c55LLU,
    [483] = 0x00cbd37400019741LLU,
    [484] = 0x4ac6b2e200956803LLU,
    [485] = 0x289b9d3f005122edLLU,
    [486] = 0x40ee37cd0081bbf9LLU,
    [487] = 0x62d8a2c600c57fdaLLU,
    [488] = 0x36819d31006ce7faLLU,
    [489] = 0x37331e10006e4aa3LLU,
    [490] = 0x03c9dff4000791dbLLU,
    [491] = 0x67d17b7700cf6f0fLLU,
    [492] = 0x48c692dc009168c3LLU,
    [493] = 0x694f1a5d00d2698eLLU,
    [494] = 0x677a9dc000cec17fLLU,
    [495] = 0x2de6f50f005bb6f7LLU,

    // 11680345^i, Jump 32
    [496] = 0x0000008000000001LLU,
    [497] = 0x28c05a6e00516c55LLU,
    [498] = 0x4ac6b2e200956803LLU,
    [499] = 0x40ee37cd0081bbf9LLU,
    [500] = 0x36819d31006ce7faLLU,
    [501] = 0x03c9dff4000791dbLLU,
    [502] = 0x48c692dc009168c3LLU,
    [503] = 0x677a9dc000cec17fLLU,

    // 11680345^i, Jump 64
    [504] = 0x0000008000000001LLU,
    [505] = 0x4ac6b2e200956803LLU,
    [506] = 0x36819d31006ce7faLLU,
    [507] = 0x48c692dc009168c3LLU,

    // 11680345^i, Jump 128
    [508] = 0x0000008000000001LLU,
    [509] = 0x36819d31006ce7faLLU,

    // 11680345^i, Jump 256
    [510] = 0x0000008000000001LLU,

    // I=16728097
    [511] = 0x7fc0000000ff4021LLU,
};

static const uint64_t args_w_Wh_16760833_512_10843986[512] = {

    // 10843986^i, Jump 1
    [0] = 0x0000008000000001LLU,
    [1] = 0x52d05cc400a57752LLU,
    [2] = 0x2c6f58aa0058c87aLLU,
    [3] = 0x2346e19500467c20LLU,
    [4] = 0x24ad2aa6004947ffLLU,
    [5] = 0x3b4673e200766f45LLU,
    [6] = 0x6ce6bd4200d99708LLU,
    [7] = 0x1fb0ba0f003f519cLLU,
    [8] = 0x38a678650071309eLLU,
    [9] = 0x20acc61100414936LLU,
    [10] = 0x7044209800e05020LLU,
    [11] = 0x22dd9ac40045a9c7LLU,
    [12] = 0x6e23d30700dc1095LLU,
    [13] = 0x71d5656800e371e1LLU,
    [14] = 0x0435fd7b000869e0LLU,
    [15] = 0x5280bd5d00a4d83bLLU,
    [16] = 0x52190af100a4090aLLU,
    [17] = 0x7d347f2300fa2a65LLU,
    [18] = 0x7333485f00e62cf8LLU,
    [19] = 0x623a874000c443f2LLU,
    [20] = 0x5799267200af0681LLU,
    [21] = 0x07697957000ecf3eLLU,
    [22] = 0x1c368c0700385efdLLU,
    [23] = 0x24f0f2980049cf6dLLU,
    [24] = 0x31b9df4600635ae2LLU,
    [25] = 0x3c8057d90078e270LLU,
    [26] = 0x291b4b2a00522209LLU,
    [27] = 0x4c8c53c80098f262LLU,
    [28] = 0x400e95e5007ffd25LLU,
    [29] = 0x693778f500d23a57LLU,
    [30] = 0x72eb5e6500e59d48LLU,
    [31] = 0x0f290e34001e4a88LLU,
    [32] = 0x188562400030fe82LLU,
    [33] = 0x2eac16d7005d40d8LLU,
    [34] = 0x2a5681f6005497d9LLU,
    [35] = 0x09c6350300138787LLU,
    [36] = 0x6f5fa87b00de87a2LLU,
    [37] = 0x3b1225ce007606c3LLU,
    [38] = 0x3967da3d0072b301LLU,
    [39] = 0x5320bfdd00a617f0LLU,
    [40] = 0x030356530006052bLLU,
    [41] = 0x2769af44004ebfaaLLU,
    [42] = 0x376997af006eb77bLLU,
    [43] = 0x18ce8408003190a1LLU,
    [44] = 0x0acf51ca0015993cLLU,
    [45] = 0x0c630b360018bfe5LLU,
    [46] = 0x3c0291680077e722LLU,
    [47] = 0x22aa7c7c004543a4LLU,
    [48] = 0x16b0e5a3002d5673LLU,
    [49] = 0x0148a5a8000290a7LLU,
    [50] = 0x73a3bbfb00e70da7LLU,
    [51] = 0x4fd5c622009f83a2LLU,
    [52] = 0x254b462c004a83e7LLU,
    [53] = 0x2a4028e000546b32LLU,
    [54] = 0x33e7f0480067b5edLLU,
    [55] = 0x4f7fa59a009ed78cLLU,
    [56] = 0x090f5c4e00121a31LLU,
    [57] = 0x091c809700123473LLU,
    [58] = 0x0c405d0b00187a9aLLU,
    [59] = 0x4ff675cd009fc4f1LLU,
    [60] = 0x1b25c35600363df4LLU,
    [61] = 0x261f9dc1004c2c2cLLU,
    [62] = 0x160e6a04002c11cdLLU,
    [63] = 0x18c3f3e400317b86LLU,
    [64] = 0x37396d24006e573eLLU,
    [65] = 0x3a5ec4f70074a05bLLU,
    [66] = 0x33078b300065f593LLU,
    [67] = 0x0fe75f48001fc6cbLLU,
    [68] = 0x0ec1293c001d7af2LLU,
    [69] = 0x176c3cf8002eccc4LLU,
    [70] = 0x1cbce51d00396b6cLLU,
    [71] = 0x2e66c102005cb64fLLU,
    [72] = 0x06d300b9000da298LLU,
    [73] = 0x3c6443540078aa55LLU,
    [74] = 0x58d68d4a00b180b0LLU,
    [75] = 0x4168d8f50082b0feLLU,
    [76] = 0x063c2c85000c753bLLU,
    [77] = 0x299faa4100532a85LLU,
    [78] = 0x4923c6a9009222fcLLU,
    [79] = 0x196c910b0032cc6cLLU,
    [80] = 0x182e8489003050f2LLU,
    [81] = 0x4ac7330200956903LLU,
    [82] = 0x6cc9ef0f00d95d7aLLU,
    [83] = 0x4b758b970096c55dLLU,
    [84] = 0x48257f98009026edLLU,
    [85] = 0x47217195008e1f53LLU,
    [86] = 0x09b7835700136a2bLLU,
    [87] = 0x11fc12f30023ef28LLU,
    [88] = 0x26030e9e004bf31cLLU,
    [89] = 0x0460e4350008bf98LLU,
    [90] = 0x07109ea1000e1db5LLU,
    [91] = 0x3a91200d007504f8LLU,
    [92] = 0x610d256800c1e9c5LLU,
    [93] = 0x4ed30c74009d7eb0LLU,
    [94] = 0x6157c18f00c27ed8LLU,
    [95] = 0x3a483b5500747353LLU,
    [96] = 0x7c36200c00f82e26LLU,
    [97] = 0x19d6c4170033a09dLLU,
    [98] = 0x7ee2e63b00fd865cLLU,
    [99] = 0x0183ba6d000306b3LLU,
    [100] = 0x602a99c600c0251fLLU,
    [101] = 0x37ec2a53006fbc5fLLU,
    [102] = 0x7898952d00f0f4dfLLU,
    [103] = 0x3406aaf70067f353LLU,
    [104] = 0x749f66e500e9047fLLU,
    [105] = 0x458d2183008af77dLLU,
    [106] = 0x7b1aea3f00f5f848LLU,
    [107] = 0x6c68e84e00d89b9dLLU,
    [108] = 0x37a56923006f2f00LLU,
    [109] = 0x7a2dff0600f41ee8LLU,
    [110] = 0x62df47ef00c58d21LLU,
    [111] = 0x53128ed100a5fb95LLU,
    [112] = 0x48cce1f00091755eLLU,
    [113] = 0x2e229a78005c2e24LLU,
    [114] = 0x6c8b185a00d8dfecLLU,
    [115] = 0x1e96336e003d1d1cLLU,
    [116] = 0x4417711800880cd7LLU,
    [117] = 0x19aa81070033482dLLU,
    [118] = 0x23d6cf1000479bb3LLU,
    [119] = 0x4a5297dc00948007LLU,
    [120] = 0x139ca61600272f7eLLU,
    [121] = 0x258072f7004aee26LLU,
    [122] = 0x51f04d4100a3b7a3LLU,
    [123] = 0x3e050984007beb11LLU,
    [124] = 0x5758e7e300ae8624LLU,
    [125] = 0x435595a200868981LLU,
    [126] = 0x4b6e78d30096b73bLLU,
    [127] = 0x6366703900c69b2eLLU,
    [128] = 0x497e62cf0092d807LLU,
    [129] = 0x79f765e000f3b1d1LLU,
    [130] = 0x3aa7551b00753157LLU,
    [131] = 0x6c5152e800d86c7eLLU,
    [132] = 0x6f621f9900de8c8fLLU,
    [133] = 0x276b191f004ec27dLLU,
    [134] = 0x19df964c0033b23dLLU,
    [135] = 0x1745eb64002e8034LLU,
    [136] = 0x2bfe69ee0057e6d5LLU,
    [137] = 0x21727dfe0042d443LLU,
    [138] = 0x23fbd7d20047e5b2LLU,
    [139] = 0x3252ff0d00648cd5LLU,
    [140] = 0x16ce5d81002d9154LLU,
    [141] = 0x7f6eac2c00fe9da2LLU,
    [142] = 0x3b971d8c00771070LLU,
    [143] = 0x603dd31500c04b88LLU,
    [144] = 0x1d275d3a003a4027LLU,
    [145] = 0x396d24900072bd93LLU,
    [146] = 0x319553a3006311ddLLU,
    [147] = 0x33fa886e0067db14LLU,
    [148] = 0x0aa6298000154700LLU,
    [149] = 0x65d6663400cb79e2LLU,
    [150] = 0x27836bb3004ef316LLU,
    [151] = 0x29cbd9cd005382ceLLU,
    [152] = 0x0671bbe9000ce03fLLU,
    [153] = 0x0ba731c100174890LLU,
    [154] = 0x04f01a820009ddbdLLU,
    [155] = 0x46d16b14008d7f6eLLU,
    [156] = 0x0bb68f9800176744LLU,
    [157] = 0x2a5057ec00548b88LLU,
    [158] = 0x117fa6580022f68dLLU,
    [159] = 0x27fca602004fe54eLLU,
    [160] = 0x3f11c833007e0408LLU,
    [161] = 0x009d93e400013ad9LLU,
    [162] = 0x4467811c0088accfLLU,
    [163] = 0x3d225759007a261eLLU,
    [164] = 0x57c61eb000af605bLLU,
    [165] = 0x7d18be3200f9f2f1LLU,
    [166] = 0x28db0e9b0051a1b0LLU,
    [167] = 0x53b9e32500a749eaLLU,
    [168] = 0x2103e5580041f749LLU,
    [169] = 0x34c87cea00697696LLU,
    [170] = 0x1d648c86003aba67LLU,
    [171] = 0x39b9ebc1007356fbLLU,
    [172] = 0x5dac613b00bb29edLLU,
    [173] = 0x4d33fe32009a4163LLU,
    [174] = 0x3c43ed3f007869b9LLU,
    [175] = 0x4aaced7100953485LLU,
    [176] = 0x576462c100ae9d14LLU,
    [177] = 0x4ea56e0d009d238aLLU,
    [178] = 0x05702e06000adda4LLU,
    [179] = 0x0d3cbca2001a72dbLLU,
    [180] = 0x0d80a21b001afa84LLU,
    [181] = 0x19f96ec20033e5e1LLU,
    [182] = 0x273c7877004e6553LLU,
    [183] = 0x51fd06f000a3d110LLU,
    [184] = 0x59cbb69400b36a88LLU,
    [185] = 0x226a3b6c0044c342LLU,
    [186] = 0x348b32180068fc1fLLU,
    [187] = 0x5253d72300a47e85LLU,
    [188] = 0x01b6d1b300036cc8LLU,
    [189] = 0x3038746d006058cdLLU,
    [190] = 0x3a6210ca0074a6f1LLU,
    [191] = 0x1b4a80850036875cLLU,
    [192] = 0x35394d1e006a57feLLU,
    [193] = 0x6392d55200c6f3e2LLU,
    [194] = 0x23e31e240047b44bLLU,
    [195] = 0x7ebc158700fd38ceLLU,
    [196] = 0x6609346700cbdf65LLU,
    [197] = 0x3cbc5e5b00795a5fLLU,
    [198] = 0x54c12f7700a957ffLLU,
    [199] = 0x0ab70035001568a5LLU,
    [200] = 0x2217813e00441df7LLU,
    [201] = 0x25b57237004b580aLLU,
    [202] = 0x098f77d400131a28LLU,
    [203] = 0x7c8d9e6b00f8dcf7LLU,
    [204] = 0x54fffa2a00a9d575LLU,
    [205] = 0x740da5f500e7e146LLU,
    [206] = 0x7bb53fd400f72ca6LLU,
    [207] = 0x04873ccb00090c36LLU,
    [208] = 0x7f342c8c00fe28c0LLU,
    [209] = 0x359c3c59006b1dabLLU,
    [210] = 0x31c4a47700637067LLU,
    [211] = 0x5a5ca5cf00b48c1eLLU,
    [212] = 0x613a47b100c243f3LLU,
    [213] = 0x70e0c1c000e18914LLU,
    [214] = 0x02855bd400050975LLU,
    [215] = 0x7c5330d000f86839LLU,
    [216] = 0x7452249500e86a21LLU,
    [217] = 0x053cef37000a7740LLU,
    [218] = 0x2ee24161005dad12LLU,
    [219] = 0x54ae5f4300a93268LLU,
    [220] = 0x1467e6650028c599LLU,
    [221] = 0x5499ad1700a9090eLLU,
    [222] = 0x184bd5dd00308b86LLU,
    [223] = 0x6041527400c05285LLU,
    [224] = 0x573fa59200ae53acLLU,
    [225] = 0x3f8bbeb0007ef7b8LLU,
    [226] = 0x37ebc2b9006fbb90LLU,
    [227] = 0x021d926200043a16LLU,
    [228] = 0x45fdf9b8008bd8f5LLU,
    [229] = 0x6e4eff5200dc66d8LLU,
    [230] = 0x1d87a54c003b0087LLU,
    [231] = 0x0d2336c1001a3fdcLLU,
    [232] = 0x5dd5df9a00bb7cd5LLU,
    [233] = 0x17bef726002f720fLLU,
    [234] = 0x2b92a4fe00570f81LLU,
    [235] = 0x772b205100ee1aacLLU,
    [236] = 0x0bfc34010017f26aLLU,
    [237] = 0x179cbd98002f2dadLLU,
    [238] = 0x1f2af81f003e465bLLU,
    [239] = 0x60fe19a500c1cbb5LLU,
    [240] = 0x36ee3cd8006dc103LLU,
    [241] = 0x0dfe5307001bf5a7LLU,
    [242] = 0x376aa873006eb99cLLU,
    [243] = 0x6664021a00cc94d3LLU,
    [244] = 0x23db13210047a439LLU,
    [245] = 0x264949ac004c7f6fLLU,
    [246] = 0x50aa5cc700a12c65LLU,
    [247] = 0x53a72ff800a7248dLLU,
    [248] = 0x6de9d00600db9cacLLU,
    [249] = 0x7884bf3700f0cd3dLLU,
    [250] = 0x0e0a0bf5001c0d13LLU,
    [251] = 0x5fa76ffc00bf1f0dLLU,
    [252] = 0x2654a984004c9629LLU,
    [253] = 0x6406a3c500c7db45LLU,
    [254] = 0x2e2c315e005c414dLLU,
    [255] = 0x26cc86fb004d85a8LLU,

    // 10843986^i, Jump 2
    [256] = 0x0000008000000001LLU,
    [257] = 0x2c6f58aa0058c87aLLU,
    [258] = 0x24ad2aa6004947ffLLU,
    [259] = 0x6ce6bd4200d99708LLU,
    [260] = 0x38a678650071309eLLU,
    [261] = 0x7044209800e05020LLU,
    [262] = 0x6e23d30700dc1095LLU,
    [263] = 0x0435fd7b000869e0LLU,
    [264] = 0x52190af100a4090aLLU,
    [265] = 0x7333485f00e62cf8LLU,
    [266] = 0x5799267200af0681LLU,
    [267] = 0x1c368c0700385efdLLU,
    [268] = 0x31b9df4600635ae2LLU,
    [269] = 0x291b4b2a00522209LLU,
    [270] = 0x400e95e5007ffd25LLU,
    [271] = 0x72eb5e6500e59d48LLU,
    [272] = 0x188562400030fe82LLU,
    [273] = 0x2a5681f6005497d9LLU,
    [274] = 0x6f5fa87b00de87a2LLU,
    [275] = 0x3967da3d0072b301LLU,
    [276] = 0x030356530006052bLLU,
    [277] = 0x376997af006eb77bLLU,
    [278] = 0x0acf51ca0015993cLLU,
    [279] = 0x3c0291680077e722LLU,
    [280] = 0x16b0e5a3002d5673LLU,
    [281] = 0x73a3bbfb00e70da7LLU,
    [282] = 0x254b462c004a83e7LLU,
    [283] = 0x33e7f0480067b5edLLU,
    [284] = 0x090f5c4e00121a31LLU,
    [285] = 0x0c405d0b00187a9aLLU,
    [286] = 0x1b25c35600363df4LLU,
    [287] = 0x160e6a04002c11cdLLU,
    [288] = 0x37396d24006e573eLLU,
    [289] = 0x33078b300065f593LLU,
    [290] = 0x0ec1293c001d7af2LLU,
    [291] = 0x1cbce51d00396b6cLLU,
    [292] = 0x06d300b9000da298LLU,
    [293] = 0x58d68d4a00b180b0LLU,
    [294] = 0x063c2c85000c753bLLU,
    [295] = 0x4923c6a9009222fcLLU,
    [296] = 0x182e8489003050f2LLU,
    [297] = 0x6cc9ef0f00d95d7aLLU,
    [298] = 0x48257f98009026edLLU,
    [299] = 0x09b7835700136a2bLLU,
    [300] = 0x26030e9e004bf31cLLU,
    [301] = 0x07109ea1000e1db5LLU,
    [302] = 0x610d256800c1e9c5LLU,
    [303] = 0x6157c18f00c27ed8LLU,
    [304] = 0x7c36200c00f82e26LLU,
    [305] = 0x7ee2e63b00fd865cLLU,
    [306] = 0x602a99c600c0251fLLU,
    [307] = 0x7898952d00f0f4dfLLU,
    [308] = 0x749f66e500e9047fLLU,
    [309] = 0x7b1aea3f00f5f848LLU,
    [310] = 0x37a56923006f2f00LLU,
    [311] = 0x62df47ef00c58d21LLU,
    [312] = 0x48cce1f00091755eLLU,
    [313] = 0x6c8b185a00d8dfecLLU,
    [314] = 0x4417711800880cd7LLU,
    [315] = 0x23d6cf1000479bb3LLU,
    [316] = 0x139ca61600272f7eLLU,
    [317] = 0x51f04d4100a3b7a3LLU,
    [318] = 0x5758e7e300ae8624LLU,
    [319] = 0x4b6e78d30096b73bLLU,
    [320] = 0x497e62cf0092d807LLU,
    [321] = 0x3aa7551b00753157LLU,
    [322] = 0x6f621f9900de8c8fLLU,
    [323] = 0x19df964c0033b23dLLU,
    [324] = 0x2bfe69ee0057e6d5LLU,
    [325] = 0x23fbd7d20047e5b2LLU,
    [326] = 0x16ce5d81002d9154LLU,
    [327] = 0x3b971d8c00771070LLU,
    [328] = 0x1d275d3a003a4027LLU,
    [329] = 0x319553a3006311ddLLU,
    [330] = 0x0aa6298000154700LLU,
    [331] = 0x27836bb3004ef316LLU,
    [332] = 0x0671bbe9000ce03fLLU,
    [333] = 0x04f01a820009ddbdLLU,
    [334] = 0x0bb68f9800176744LLU,
    [335] = 0x117fa6580022f68dLLU,
    [336] = 0x3f11c833007e0408LLU,
    [337] = 0x4467811c0088accfLLU,
    [338] = 0x57c61eb000af605bLLU,
    [339] = 0x28db0e9b0051a1b0LLU,
    [340] = 0x2103e5580041f749LLU,
    [341] = 0x1d648c86003aba67LLU,
    [342] = 0x5dac613b00bb29edLLU,
    [343] = 0x3c43ed3f007869b9LLU,
    [344] = 0x576462c100ae9d14LLU,
    [345] = 0x05702e06000adda4LLU,
    [346] = 0x0d80a21b001afa84LLU,
    [347] = 0x273c7877004e6553LLU,
    [348] = 0x59cbb69400b36a88LLU,
    [349] = 0x348b32180068fc1fLLU,
    [350] = 0x01b6d1b300036cc8LLU,
    [351] = 0x3a6210ca0074a6f1LLU,
    [352] = 0x35394d1e006a57feLLU,
    [353] = 0x23e31e240047b44bLLU,
    [354] = 0x6609346700cbdf65LLU,
    [355] = 0x54c12f7700a957ffLLU,
    [356] = 0x2217813e00441df7LLU,
    [357] = 0x098f77d400131a28LLU,
    [358] = 0x54fffa2a00a9d575LLU,
    [359] = 0x7bb53fd400f72ca6LLU,
    [360] = 0x7f342c8c00fe28c0LLU,
    [361] = 0x31c4a47700637067LLU,
    [362] = 0x613a47b100c243f3LLU,
    [363] = 0x02855bd400050975LLU,
    [364] = 0x7452249500e86a21LLU,
    [365] = 0x2ee24161005dad12LLU,
    [366] = 0x1467e6650028c599LLU,
    [367] = 0x184bd5dd00308b86LLU,
    [368] = 0x573fa59200ae53acLLU,
    [369] = 0x37ebc2b9006fbb90LLU,
    [370] = 0x45fdf9b8008bd8f5LLU,
    [371] = 0x1d87a54c003b0087LLU,
    [372] = 0x5dd5df9a00bb7cd5LLU,
    [373] = 0x2b92a4fe00570f81LLU,
    [374] = 0x0bfc34010017f26aLLU,
    [375] = 0x1f2af81f003e465bLLU,
    [376] = 0x36ee3cd8006dc103LLU,
    [377] = 0x376aa873006eb99cLLU,
    [378] = 0x23db13210047a439LLU,
    [379] = 0x50aa5cc700a12c65LLU,
    [380] = 0x6de9d00600db9cacLLU,
    [381] = 0x0e0a0bf5001c0d13LLU,
    [382] = 0x2654a984004c9629LLU,
    [383] = 0x2e2c315e005c414dLLU,

    // 10843986^i, Jump 4
    [384] = 0x0000008000000001LLU,
    [385] = 0x24ad2aa6004947ffLLU,
    [386] = 0x38a678650071309eLLU,
    [387] = 0x6e23d30700dc1095LLU,
    [388] = 0x52190af100a4090aLLU,
    [389] = 0x5799267200af0681LLU,
    [390] = 0x31b9df4600635ae2LLU,
    [391] = 0x400e95e5007ffd25LLU,
    [392] = 0x188562400030fe82LLU,
    [393] = 0x6f5fa87b00de87a2LLU,
    [394] = 0x030356530006052bLLU,
    [395] = 0x0acf51ca0015993cLLU,
    [396] = 0x16b0e5a3002d5673LLU,
    [397] = 0x254b462c004a83e7LLU,
    [398] = 0x090f5c4e00121a31LLU,
    [399] = 0x1b25c35600363df4LLU,
    [400] = 0x37396d24006e573eLLU,
    [401] = 0x0ec1293c001d7af2LLU,
    [402] = 0x06d300b9000da298LLU,
    [403] = 0x063c2c85000c753bLLU,
    [404] = 0x182e8489003050f2LLU,
    [405] = 0x48257f98009026edLLU,
    [406] = 0x26030e9e004bf31cLLU,
    [407] = 0x610d256800c1e9c5LLU,
    [408] = 0x7c36200c00f82e26LLU,
    [409] = 0x602a99c600c0251fLLU,
    [410] = 0x749f66e500e9047fLLU,
    [411] = 0x37a56923006f2f00LLU,
    [412] = 0x48cce1f00091755eLLU,
    [413] = 0x4417711800880cd7LLU,
    [414] = 0x139ca61600272f7eLLU,
    [415] = 0x5758e7e300ae8624LLU,
    [416] = 0x497e62cf0092d807LLU,
    [417] = 0x6f621f9900de8c8fLLU,
    [418] = 0x2bfe69ee0057e6d5LLU,
    [419] = 0x16ce5d81002d9154LLU,
    [420] = 0x1d275d3a003a4027LLU,
    [421] = 0x0aa6298000154700LLU,
    [422] = 0x0671bbe9000ce03fLLU,
    [423] = 0x0bb68f9800176744LLU,
    [424] = 0x3f11c833007e0408LLU,
    [425] = 0x57c61eb000af605bLLU,
    [426] = 0x2103e5580041f749LLU,
    [427] = 0x5dac613b00bb29edLLU,
    [428] = 0x576462c100ae9d14LLU,
    [429] = 0x0d80a21b001afa84LLU,
    [430] = 0x59cbb69400b36a88LLU,
    [431] = 0x01b6d1b300036cc8LLU,
    [432] = 0x35394d1e006a57feLLU,
    [433] = 0x6609346700cbdf65LLU,
    [434] = 0x2217813e00441df7LLU,
    [435] = 0x54fffa2a00a9d575LLU,
    [436] = 0x7f342c8c00fe28c0LLU,
    [437] = 0x613a47b100c243f3LLU,
    [438] = 0x7452249500e86a21LLU,
    [439] = 0x1467e6650028c599LLU,
    [440] = 0x573fa59200ae53acLLU,
    [441] = 0x45fdf9b8008bd8f5LLU,
    [442] = 0x5dd5df9a00bb7cd5LLU,
    [443] = 0x0bfc34010017f26aLLU,
    [444] = 0x36ee3cd8006dc103LLU,
    [445] = 0x23db13210047a439LLU,
    [446] = 0x6de9d00600db9cacLLU,
    [447] = 0x2654a984004c9629LLU,

    // 10843986^i, Jump 8
    [448] = 0x0000008000000001LLU,
    [449] = 0x38a678650071309eLLU,
    [450] = 0x52190af100a4090aLLU,
    [451] = 0x31b9df4600635ae2LLU,
    [452] = 0x188562400030fe82LLU,
    [453] = 0x030356530006052bLLU,
    [454] = 0x16b0e5a3002d5673LLU,
    [455] = 0x090f5c4e00121a31LLU,
    [456] = 0x37396d24006e573eLLU,
    [457] = 0x06d300b9000da298LLU,
    [458] = 0x182e8489003050f2LLU,
    [459] = 0x26030e9e004bf31cLLU,
    [460] = 0x7c36200c00f82e26LLU,
    [461] = 0x749f66e500e9047fLLU,
    [462] = 0x48cce1f00091755eLLU,
    [463] = 0x139ca61600272f7eLLU,
    [464] = 0x497e62cf0092d807LLU,
    [465] = 0x2bfe69ee0057e6d5LLU,
    [466] = 0x1d275d3a003a4027LLU,
    [467] = 0x0671bbe9000ce03fLLU,
    [468] = 0x3f11c833007e0408LLU,
    [469] = 0x2103e5580041f749LLU,
    [470] = 0x576462c100ae9d14LLU,
    [471] = 0x59cbb69400b36a88LLU,
    [472] = 0x35394d1e006a57feLLU,
    [473] = 0x2217813e00441df7LLU,
    [474] = 0x7f342c8c00fe28c0LLU,
    [475] = 0x7452249500e86a21LLU,
    [476] = 0x573fa59200ae53acLLU,
    [477] = 0x5dd5df9a00bb7cd5LLU,
    [478] = 0x36ee3cd8006dc103LLU,
    [479] = 0x6de9d00600db9cacLLU,

    // 10843986^i, Jump 16
    [480] = 0x0000008000000001LLU,
    [481] = 0x52190af100a4090aLLU,
    [482] = 0x188562400030fe82LLU,
    [483] = 0x16b0e5a3002d5673LLU,
    [484] = 0x37396d24006e573eLLU,
    [485] = 0x182e8489003050f2LLU,
    [486] = 0x7c36200c00f82e26LLU,
    [487] = 0x48cce1f00091755eLLU,
    [488] = 0x497e62cf0092d807LLU,
    [489] = 0x1d275d3a003a4027LLU,
    [490] = 0x3f11c833007e0408LLU,
    [491] = 0x576462c100ae9d14LLU,
    [492] = 0x35394d1e006a57feLLU,
    [493] = 0x7f342c8c00fe28c0LLU,
    [494] = 0x573fa59200ae53acLLU,
    [495] = 0x36ee3cd8006dc103LLU,

    // 10843986^i, Jump 32
    [496] = 0x0000008000000001LLU,
    [497] = 0x188562400030fe82LLU,
    [498] = 0x37396d24006e573eLLU,
    [499] = 0x7c36200c00f82e26LLU,
    [500] = 0x497e62cf0092d807LLU,
    [501] = 0x3f11c833007e0408LLU,
    [502] = 0x35394d1e006a57feLLU,
    [503] = 0x573fa59200ae53acLLU,

    // 10843986^i, Jump 64
    [504] = 0x0000008000000001LLU,
    [505] = 0x37396d24006e573eLLU,
    [506] = 0x497e62cf0092d807LLU,
    [507] = 0x35394d1e006a57feLLU,

    // 10843986^i, Jump 128
    [508] = 0x0000008000000001LLU,
    [509] = 0x497e62cf0092d807LLU,

    // 10843986^i, Jump 256
    [510] = 0x0000008000000001LLU,

    // I=16728097
    [511] = 0x7fc0000000ff4021LLU,
};
